### ISSUE TITLE
Not working properly on iOS 7 ?

### ISSUE THREAD

**Issue by fohoizey** [aFarkas/lazysizes#142]
Hi

I'm using an iPad Air on iOS 7 and only the few first pictures load.
When scrolling, i can see that pictures above the fold never load.

No issue on iOS 8, Android, Mac OS X Safari, Firefox, Chrome, ...

Is it a known issue ? How to handle it ?

Thanks

**Comment by doronfeldman** [comment]
IOS 7 does not fire scroll events while scrolling

read this,
http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/

**Comment by aFarkas** [comment]
I assume above the fold images do load as soon as you scroll them into view? In case you want to force load of above fold images you can use the code here:https://github.com/aFarkas/lazysizes/issues/139#issuecomment-128746152 . But you won't get it to download while the User is scrolling because painting us also paused while scrolling.

**Comment by aFarkas** [comment]
In case all in view/near view images are loaded as soon as you stop scrolling, I can't consider this as a bug.

It is a constrain of iOS7 (http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/). Please re-open, if you see other issues.
