### ISSUE TITLE
Image shrinks without cause when resizing

### ISSUE THREAD

**Issue by threegoldstone** [aFarkas/lazysizes#156]
I set a image with data-srcset and data-sizes="auto", but i do not set the width, the width is set by css. Attributes i set is like https://github.com/aFarkas/lazysizes#modern-transparent-srcset-pattern. The img tag's parent doesn't have the width either, so before the image is loaded, the width is 0. After the image loaded, it has the intrinsic width, but when i resize the window, its sizes shrink to 1px. I am using React. Excellent tool, btw.

**Comment by aFarkas** [comment]
Basically the image width must be computable by script/CSS before it is loaded, otherwise lazysizes can't compute the correct size.

However lazysizes has some small correction algorithm and goes up the DOM tree until it finds a width that is larger than `minSize` (40). Therefore I really need to see an example to check whether this is a bug or by design. Can you create either a test case, give me a link or a zip with the full React app?

In case this should be by design, you have always the possibility to modify the computed sizes to fit your special needs:

```js
document.addEventListener('lazybeforesizes', function(e){
     //get computed size as number
     var oldSize = e.detail.width;

     //set width to correct to your needs:
     e.detail.width = computeWidth(e.target, e.detail.width);
});
```

**Comment by threegoldstone** [comment]
sure, i will try to give you a link with full React app this weekend.

**Comment by aFarkas** [comment]
@threegoldstone 
Any news on this?

**Comment by aFarkas** [comment]
Please re-open if the problem still exists and you can provide a test case.
