### ISSUE TITLE
src is set after load, lazyload class present, image not painting

### ISSUE THREAD

**Issue by argyleink** [aFarkas/lazysizes#157]
occasionally, across mobile, desktop and heavy often in IE 11, the images are lazyloaded (verified in network), and the src property is set to the correct image path (verified in DOM), but the image never paints/renders. this could be something to do with my implementation (doubtful, but possible), but the inconsistent behavior leads me to think it's something else. Have you seen this? I'll try to get a confirmed repro scenario, but for now, IE10 and IE11 struggle to display an image after lazyloading. 

ideas?

**Comment by aFarkas** [comment]
No, I haven't something like this and also not heard of. The only thing I heard of was this: https://github.com/aFarkas/lazysizes/issues/136

But I couldn't replicate. Can you give me a link so that I can check this? Thanks.

**Comment by argyleink** [comment]
seems to be the result of having dev tools open and a browser issue not rending the image after src is set.

**Comment by aFarkas** [comment]
@argyleink 
Thx, for reporting. I also checked your site and couldn't replicate it using IE11 and Chrome. 

I would advice, that you don't use lazysizes for your hero image. This is a crucial image and is always above the fold. lazyloading should be more treated as a resource prioritization tool. Images that are crucial and above the fold shouldn't be lazyloaded, while other should. This way the crucial images can load much faster. lazysizes also does a lot to improve this. For example it first only checks whether images are in view and if not it starts to preload images below the fold, so that the user doesn't have to wait as soon as he scrolls there. But you can improve this your own by simply not using lazysizes on this image.

There might be sometimes some exceptions, for example: I often also still use lazysizes for crucial above the fold images, because the ``data-sizes="auto"`` feature gives me separation of concerns and allows me to implement responsive images easily in any environment. But in your case you simply just use a `data-src` so you could switch to `src` back again.

**Comment by argyleink** [comment]
superb advice

**Comment by argyleink** [comment]
after further investigation, it could have been related to browser caching also..
