### ISSUE TITLE
iOS sizes="auto" loads 2 images.

### ISSUE THREAD

**Issue by peterlenagh** [aFarkas/lazysizes#160]
![web inspector](http://i.imgur.com/jAHAuTC.jpg)

In the example above both `https://farm9.staticflickr.com/8200/8248153196_7a7664e147_c.jpg` and `https://farm9.staticflickr.com/8200/8248153196_7a7664e147_m.jpg` are loaded. I have seen the same thing with my own implementation.

Is this expected behaviour? Is it avoidable? I'm using respimage polyfill along with lazysizes and marking up images like this (in the case below, I also see both images load on iOS):

```
<img class="lazyload" data-srcset="//placehold.it/320x320/ff0000 320w, //placehold.it/640x640/00ff00 640w," data-sizes="auto" />
```

Thanks for your time, excellent work on lazysizes.

**Comment by aFarkas** [comment]
Yes, this is a iOS 8 bug, which is fixed in iOS9.

Yes, you can avoid it. By using this plugin, additionally to your respimage or picturefill polyfill:
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/fix-ios-sizes

Note: This plugin is already automatically included in the respimg plugin.

Another way to workaround would be by using the following markup:

```html
<picture>
    <source  data-srcset="//placehold.it/320x320/ff0000 320w, //placehold.it/640x640/00ff00 640w,"/>
    <img data-src="//placehold.it/640x640/00ff00" class="lazyload" data-sizes="auto" />
</picture>
```

**Comment by peterlenagh** [comment]
Amazing. Thanks!
