### ISSUE TITLE
e.detail.width

### ISSUE THREAD

**Issue by tom-c** [aFarkas/lazysizes#180]
Hey, I'm having some problems with access / setting the e.detail object, as per the guide for modifying sizes on 'lazybeforesizes'. In both Chrome and Safari it's not available and throws an error but I can access / set to achieve what I want using e.originalEvent.detail?

I need to manually set the 'sizes' of a picture based on it's aspect ratio and the height of the browser, given that I know the aspect already it seems better to do a simple callback based change than use the parent-fit plugin.

Not sure if this is a bug or specific to me, I'm using jquery 1.11.1, and latest Safari (9.0.1) and Chrome (46)…

Ideas gratefully received :)

**Comment by aFarkas** [comment]
@tom-c 

Yeah, jQuery doesn't give you the real event object. It does so o by copying some properties to a fake event object. This is why `e.detail` is `undefined`, if used with jQuery. I think they fixed it in jQuery 3.0 (just for the detail property).

As you already suspected the `e.originalEvent` is what you need if you use jQuery.

You can also write it jQuery agnostic:

```js
(e.orginalEvent || e).detail.width = 333;
```

> given that I know the aspect already it seems better to do a simple callback based change than use the parent-fit plugin.

I'm happy that someone is using the API instead of relying on plugins. ;-)

**Comment by tom-c** [comment]
Thanks for that, glad I'm not going mad. I've slipped in that switch too for future jquery migration :)

Thanks for all the work on Lazysizes too, am enjoying using it!
