### ISSUE TITLE
Limit the preloaded images. 

### ISSUE THREAD

**Issue by gladsonrobinson** [aFarkas/lazysizes#181]
Am using Owl Carousel to make a slide image. Need only to display 4 images. And need to achieve  lazy load for images. 
Have tried to use your plug-in, it works such as loading the first 3 images on the first time and on slide it loads the 4th image. 
My requirement is to load first 2 images on first time and on slide to load the consecutive images.
Like when I view the first slide image the second slide image should be pre loaded. And when I go to second slide the third image should be loaded as well. 

Is there any way to achieve this.

**Comment by aFarkas** [comment]
Yes, this is basically possible. But lazysizes is actually quite good in distinguishing preload time and crucial loading time.

In case your owl carousel is above the fold and you load it you will likley experience the following:

lazysizes first only loads the first image and then loads the other two images. This means although lazysizes loads a little bit more than you want, the crucial thing(s) have a higher priority in download. This was an important part in designing lazysizes. And for me it was also important, that near the view images are always preloaded.

I really would suggest that you live with this. I don't think it is bad behavior.

If you want to change this, here is how you can do so:

```js
//the configuration should be done before lazysizes and immediately (not inside a domready wrapper):
window.lazySizesConfig = window.lazySizesConfig || {};

window.lazySizesConfig.expand = 225;
window.lazySizesConfig.expFactor = 1.4;
```

In case your owl carousel does not span the hole viewport width, you might also add the attribute ``data-expand="auto"`` to all lazyload elements inside of your carousel.

The `data-expand` attribute is normally used for something else (I.e.: To override the JS config for `expand` and `expFactor`). But in case it is not a number it still uses the JS configuration, but forces lazysizes to always check for nesting visibility. (This also adds some CPU performance penalty.)

**Comment by gladsonrobinson** [comment]
Thank you @aFarkas  Will look on it. And thanks lot for your suggestion.

**Comment by aFarkas** [comment]
@gladsonrobinson 
I have added a new option (`hFac`). Which allows you to modify the horizontal expand without changing the vertical expand. 


With this you can do this:

```js
//the configuration should be done before lazysizes and immediately (not inside a domready wrapper):
window.lazySizesConfig = window.lazySizesConfig || {};

window.lazySizesConfig.hFac = 0.4;
```

As I said, this won't give you full control (unless you use the `data-expand` attribute), but should come closer to your needs without sacrificing the normal preload. 

This option is currently only available in the master branch.

**Comment by hecktarzuli** [comment]
Speaking of carousels, I'm using Vue-Carousel and for the life of me, I can't get lazysizes to not load the first 2 large images at the same time.  I've tried this for giggles:

window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.loadMode = 0
window.lazySizesConfig.expand = 0
window.lazySizesConfig.expFactor = 0
window.lazySizesConfig.hFac = 0

and it looks like these settings are taking effect because things don't really load until the second I see them (which I know isn't ideal, but great for testing configs) ..No matter what, even when I have 2 images with 100px margin between them, they still load at the same time (2 out of 12). 

I'd really like the 1st large image to load, and then wait until prloadAfterLoad time to fetch the rest.

![image](https://user-images.githubusercontent.com/2112282/41855697-e41815c4-7858-11e8-940f-7cae0e42ec3e.png)
