### ISSUE TITLE
Use auto-sizing without lazyloading

### ISSUE THREAD

**Issue by syropian** [aFarkas/lazysizes#185]
Is there a way we could natively load all images, but still make use of lazySizes great auto-sizing feature? We want our images to load as fast as possible, but we could cut a lot of repetitive dev time by using the auto-size feature.

**Comment by aFarkas** [comment]
Have you tried:

```js
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.preloadAfterLoad = true;
```

Or is this not what you want?

**Comment by aFarkas** [comment]
@syropian 
Does this `lazySizesConfig.preloadAfterLoad` work for you or do you need something else?

In general, what's the problem in getting lazy loading for free?

**Comment by neatonk** [comment]
This works for me...

```html
<img src="image.jpg" class="lazyload" data-sizes="auto" />
```

**Comment by yoannisj** [comment]
@aFarkas I have found the use of `data-sizes="auto"` without lazyloading interesting for images that are above the fold (or at least, the first image on the page).

Indeed, (as google pagespeed insights points out) you don't want to lazyload these images. But you still might want to use a responsive image there. In that case, being able to use lazysizes' `data-sizes="auto"` feature can be helpful instead of setting the `sizes` attribute manually.

@syropian By digging into the code, I have found out is actually possible, but you need to add the `lazyautosizes` (or whatever custom class you have set in the `lazySizesConfig.autosizesClass` option) class to your `<img />` and manually call `lazySizes.autoSizer.checkElems()` on page load.

@aFarkas running `lazySizes.autoSizer.checkElems()` sets the `size` attribute for all images with the autosizesClass (including images that are lazyloaded, which don't need this to happen until they actually get loaded).

It would be great if there was an easier way to use `data-sizes="auto"` on images that are loaded natively – so that the `sizes`attribute is set automatically on page load for these images, but not for images that get lazyloaded.

**Comment by aFarkas** [comment]
@yoannisj 
This doesn't work. If you do not lazyload those images, the browser will start to download the first images with the native default (i.e.: `sizes="100vw"`) as soon as lazySizes kicks in the `sizes` is changed and the browser will either abort the old request and start to load the new smaller one, still load the bigger one or even download both the big one and the adjusted smaller one.

In general you can not win this fight. The only thing, that you can do in these cases, is to make sure that lazySizes kicks in as soon as possible.

You should read this: https://github.com/aFarkas/lazysizes#tip-wherehow-to-include-lazysizes

You can also compare the following waterfalls:
Not optimized: https://www.webpagetest.org/result/161108_E4_111Q/1/details/#waterfall_view_step1
Optimized: https://www.webpagetest.org/result/161127_8W_VYY/3/details/#waterfall_view_step1

Please compare how the image (request 11) is loaded compared to the script execution of the main script (request 8). To do this you should do this (Note: This should only work with lazySizes 3.x.x):

```
<script src="_crucial-behavior.js"></script> <!-- includes lazySizes + plugins. should have the async attribute, if it is loaded before any images, should not have the async attribute if it is loaded after a lazyload image, but must **never** have the defer attribute -->
<script src="_app-behavior.js" defer=""></script> <!-- should have a defer attribute -->
```

The content of the _crucial-behavior should be as light as possible and should include the following lines at the end:

```js
if(document.querySelector('.lazyload')){ //if you load the script at the bottom you don't need to test this, just call init
    lazySizes.init();
}
```

The content of the _app-behavior.js can include the following lines (not really important though)

```js
if(document.querySelector('.lazyload')){
    if(lazySizes.init.i){
        lazySizes.rAF._lsFlush();
    } else {
        lazySizes.init();
    }
}
```
