### ISSUE TITLE
Safari loading two images

### ISSUE THREAD

**Issue by r1987** [aFarkas/lazysizes#186]
I know that the *picture* element isn't supported on Safari, but I noticed a wierd thing on my setup of lazysizes and picturefill.

I first discovered an console error on safari with this setup I have:

```html
<div class="ratio-box" style="padding-top:66.6666666667%">
    <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
    <source data-srcset="image-280x187.jpg 1x, image-280x187@2x.jpg 2x"
    media="(max-width: 480px)">
    <source data-srcset=
    "image-660x440.jpg 1x, image-660x440@2x.jpg 2x"
    media="(max-width: 1024px)">
    <source data-srcset=
    "image-930x620.jpg 1x, image-930x620@2x.jpg 2x"
    media="(max-width: 1400px)">
    <source data-srcset=
    "image-930x620.jpg 1x, image-930x620@2x.jpg 2x">
    <!--[if IE 9]></video><![endif]-->
    <img alt="image with artdirection"
    class="lazyload" data-src=
    "image-930x620.jpg 1x, image-930x620@2x.jpg 2x"
    src=
    "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="></picture>
</div>
```

This gives me a 404 in the console. It seems that it reads the whole data-src attribute as an address:

```javascript
Failed to load resource: http://image-930x620.jpg%201x,%20image-930x620@2x.jpg%202x
the server responded with a status of 404 (Not Found)
```
I don't actually even know, if its possible to use the 1x and 2x in an image tag in this context (?!). 
Anyhow, i removed the markup like that and replaced the data-src with just the address to the non-retina image in the *img* tag. That sort of solved the problem, but then I noticed that the browser loads both the *fallback image* and the image specific for the *screen size*. So I would see both images appear in the resources if viewing Safari at ipad size:

- image-660x440.jpg
- image-930x620.jpg

Same goes for mobile size.

Is this a case with the new Safari 9 or what am I doing wrong?

**Comment by aFarkas** [comment]
> I don't actually even know, if its possible to use the 1x and 2x in an image tag in this context (?!). 

You can't define descriptors inside of a `src` attribute, you must use the `srcset`/`data-srcset`. And you already did by defining these at the last `source` element.

At the end your new markup should be correct:

```html
<div class="ratio-box" style="padding-top:66.6666666667%">
    <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
    <source data-srcset="image-280x187.jpg 1x, image-280x187@2x.jpg 2x"
    media="(max-width: 480px)">
    <source data-srcset=
    "image-660x440.jpg 1x, image-660x440@2x.jpg 2x"
    media="(max-width: 1024px)">
    <source data-srcset=
    "image-930x620.jpg 1x, image-930x620@2x.jpg 2x"
    media="(max-width: 1400px)">
    <source data-srcset=
    "image-930x620.jpg 1x, image-930x620@2x.jpg 2x">
    <!--[if IE 9]></video><![endif]-->
    <img alt="image with artdirection"
    class="lazyload" data-src=
    "image-930x620.jpg"
    src=
    "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="></picture>
</div>
```

I assume, that you have included lazysizes before picturefill. It might happen that at the time where lazysizes transforms the image picturefill isn't loaded yet and lazysizes goes into fallback mode (loads the `data-src` in non supporting browsers. Then later picturefill kicks in and loads the normal responsive image.

You have two options to fix this:
1. Move picturefill higher so that it can be used at once with lazysizes
2. Define a lazysizes polyfill

```js
window.lazySizesConfig = window.lazySizesConfig || {};

window.lazySizesConfig.pf = function(options){
    if(window.picturefill){
        window.picturefill(options);
    }
};
```

A small tip: In my eyes the 1x/2x pattern is dead. And can be always substituted with the compressive image pattern. Which means, that you only serve the 2x images but with a much higher compression. At the end the image size for the 2x will be lower than of the 1x image. You markup would then look like this:

```html
<div class="ratio-box" style="padding-top:66.6666666667%">
    <picture>
    <!--[if IE 9]><video style="display: none;><![endif]-->
    <source data-srcset="image-280x187@2x-highly-compressed.jpg 2x"
    media="(max-width: 480px)">
    <source data-srcset=
    "image-660x440@2x-highly-compressed.jpg 2x"
    media="(max-width: 1024px)">
    <source data-srcset=
    "image-930x620@2x-highly-compressed.jpg 2x"
    media="(max-width: 1400px)">
    <source data-srcset=
    "image-930x620@2x-highly-compressed.jpg 2x">
    <!--[if IE 9]></video><![endif]-->
    <img alt="image with artdirection"
    class="lazyload" data-src=
    "image-930x620.jpg"
    src=
    "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="></picture>
</div>
```

**Comment by r1987** [comment]
Thanks for a quick answer. Its true, picturefill was loaded after lazysizes, so I placed it before lazysizes, but Safari still loads 2 images after this.

By compressive image pattern you mean that the 2x image should have extra compression by reducing the quality?

**Comment by aFarkas** [comment]
> ..., but Safari still loads 2 images after this.

Then I need a testcase or link to your page/prototype, because I can't reproduce this. If you are using the async attribute on picturefill, it might be still loaded after lazysizes.

> By compressive image pattern you mean that the 2x image should have extra compression by reducing the quality?

Yes, you the perceived quality is the same, but you can compress it really high. Here are some informations:
- https://www.filamentgroup.com/lab/compressive-images.html
- http://imageoptimization.info/Compressive

**Comment by r1987** [comment]
Here's my page: http://urlgone.com/0b968f/

**Comment by aFarkas** [comment]
I haven't looked deeper into this. Because you have an old version of lazysizes. As I can recall you could fix this by changing your markup to this:

If you update to version 1.3.1 everything should be fine.

**Comment by r1987** [comment]
Brilliant! Seems to fix everything.
