### ISSUE TITLE
Alt attribute not working

### ISSUE THREAD

**Issue by simon-webup** [aFarkas/lazysizes#194]
Hi !

When I fill in the "alt" attribute in an image while it's processed through *lazysizes* and *RIaS plugin*, the only visible image is the smallest version.

Here is my code : 
```html
<img class="lazyload" data-src="path/to/my/img-{width}.jpg" data-format="full" data-sizes="auto" alt="foobar">
```
If I leave it empty, it works like a charm.

Oddly, it works well if I write less than 5 letters in the attribute, and it seems to be used in order to make some kind of calculations : the image's width is calculated on the basis of the size of the "alt" text as it's displayed on the web page.

Regards.

**Comment by aFarkas** [comment]
I suspect, that you don't specify the width of your image in your CSS.

From the documentation:

Important: How sizes is calculated: The automatic sizes calculation uses the width of the image. If it is below 40 (can be configured through the minSize option), lazysizes traverses up the DOM tree until it finds a parent which is over 40 and uses this number. Often the following general CSS rule might help: `img[data-sizes="auto"] { display: block; width: 100%; }` (see also [specifying image/iframe dimensions](https://github.com/aFarkas/lazysizes#specify-dimensions)).

This means, if you have no `alt` your image is smaller than 40 and lazySizes tries to get the width from a parent element otherwise it uses the width of the element itself. 

I suggest that you always specify the width of your image.

**Comment by simon-webup** [comment]
Thank you, you were right.
It works pretty well right now.
