### ISSUE TITLE
img with absolute / min-width positioning increases `sizes` attr on scroll

### ISSUE THREAD

**Issue by lunelson** [aFarkas/lazysizes#242]
This issue happens when positioning images in set width/height containers using `position: absolute` and  `width/height`, `min-width/-height`, `max-width/-height` etc. so as to mimic `object-fit: cover` (because `object-fit` is not supported in IE). There are two problems:

1. the wrong size often seems to be chosen (too big); but worse is
2. on iOS when scrolling, the `sizes` attribute continues to be updated: causing ever-larger images to be loaded (adding bandwidth), and causing the image to 'zoom in' until unrecognizable (when it arrives at the largest source).

Please see the debug view, on iOS or Simulator: http://s.codepen.io/lunelson/debug/EKjKKj

Pen here: http://codepen.io/lunelson/pen/EKjKKj

**Comment by aFarkas** [comment]
This is answered in the documentation. You might want to check out the [parent fit plugin](plugins/parent-fit).

But read this:

**Important: How ``sizes`` is calculated**: The automatic sizes calculation uses the display width of the image. This means that the width of the image has to be calculable at least approximately before the image itself is loaded. Often the following general CSS rule might help: ``img[data-sizes="auto"] { display: block; width: 100%; }`` (see also [specifying image/iframe dimensions with the recommended aspect ratio definition](#specify-dimensions)). If it is below ``40`` (can be configured through the ``minSize`` option), lazysizes traverses up the DOM tree until it finds a parent which is over ``40`` and uses this number.

The width auto-calculated by lazysizes can be modified using the ``lazybeforesizes`` event ([lazybeforesizes documentation](#lazybeforesizes-documentation)). Alternatively, the [parent fit plugin](plugins/parent-fit) can be used for sizing images to fit a parent / container, and is the only solution when an image's height needs to be taken into account when fitting it to its container.

The ``data-sizes="auto"`` feature only makes sense if you use the ``data-srcset`` attribute with *width* descriptors which allows the most appropriate image can be selected (It does not make sense if you use the x descriptor or only ``src``.).

**Comment by lunelson** [comment]
Thanks, but I am aware of most of that. Maybe my first observation was a distraction. The bug is that on iOS the `sizes` attribute *continues* to be updated with larger and larger numbers, causing new images to load, until the largest source is reached. Did you try the debug pen on iOS? You might need to try it on a Retina device. On first load, `sizes` is calculated correctly; but if you scroll up and down a bit, it will keep swapping out `sizes` with new values. It seems to me, it is swapping the first calculated `sizes` value, for the width value of the current source, which on retina leads to loading a source double that size, and repeats this until it runs out of sources.

The following is Simulator running an iPhone 4s

![ios-sizes](https://cloud.githubusercontent.com/assets/1242864/13467707/b73457dc-e09f-11e5-9647-fcf9eee12352.gif)

**Comment by aFarkas** [comment]
> Thanks, but I am aware of most of that.  Maybe my first observation was a distraction....

I think you are a little bit distracted by the fact, that this bug only seems to happen in Safari. 

In fact it is working as designed and as documented, if you don't specify the width width CSS or markup, you have to use the JS event API, otherwise it can go wrong, 

A solution for your specifc need is the [parent fit plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/parent-fit).

To remove your "distraction" ;-), here is what is happening:

1. First the image is below 40 pixel width and lazysizes automatically takes the parent container (let's say it's 320)
2. now Safari loads the 640 image to satisfy the set sizes="320px" (2x for retina). 
3. because Safari doesn't fully support sizes and **you don't specify the width with CSS or JS** the image is displayed at 640 display
4. by scrolling up and down, Safari triggers a resize event (The adressbar changes the height) and lazysizes recalculates the width...
5. lazysizes detects, that the width of the image is now 640, sets the width and...
6. safari loads the 1280 image to satisfy retina and this 1280 image is then displayed at 1280 and not 640.
7. repeat........


At the end it all comes down to two simple facts a) it doesn't work because you don't set the image width and b) you don't want the image width, but you want the container width to be used.

And for this task I have created a plugin, called  [parent fit plugin](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/parent-fit).

If you don't want to use it, you can write your own:

This could be a start (also documented in the readme):

```js
$(document).on('lazybeforesizes', function(e){
    //use width of parent node instead of the image width itself
   var $image = $(e.target);
    if($image.is('.hold > img')){
        e.detail.width = $image.closest(':not(picture)').width() || e.detail.width;
        //set the width so that safari doesn't use image pixel -> layout pixel and stays in layout pixel land.
        $image.attr('width', e.detail.width);
    }
});
```

**Comment by aFarkas** [comment]
Btw.: here is a working demo:
http://jsfiddle.net/trixta/w96o9xm5/

**Comment by lunelson** [comment]
Ah. Okay so if I understand correctly now:

1. I've been doing it wrong, because I'm sizing images implicitly (with `min-width`, `max-height`, etc.) rather than explictly (`width` and `height` values in the CSS or HTML); but I didn't really notice this because the script is falling back to a reasonable calculation in most browsers;
2. iOS Safari has a double-bug because it triggers a `resize` event when scrolling causes the browser header to expand/collapse.

So I'm going to try this with parent-fit. Questions:

1. does it matter which order I supply the width/height values in `data-srcset`? i.e. `200w 300h` vs. `300h 200w`
2. does supplying said height value break the `srcset` syntax (on browsers that support srcset), and/or should I just supply the `h` value on the first `src` in the `srcset`?
3. Since I'm always placing the `img` in some kind of container even when not doing "cover" or "contain" sizing (i.e. I'm using the intrinsic-aspect-ratio thing otherwise), should I output `data-parent-fit='width'` as a default, when neither `cover` nor `contain` is desired?

Thanks for your detailed responses.

**Comment by aFarkas** [comment]
1. First both questions:
yes.

----------------

> 1. does it matter which order I supply the width/height values in data-srcset?

No, order does not matter.

> 2. does supplying said height value break the srcset syntax

It shouldn't, because it is standardized, but there is a [Edge 13 bug](https://connect.microsoft.com/IE/feedbackdetail/view/2405716/srcset-parser-for-img-source-elements-lacks-support-of-the-future-compat-h-descriptor-parsing). I have fixed this in the upcoming version of lazysizes.

> or should I just supply the h value on the first src in the srcset?

This would be also a good workaround (Edge won't select this image candidate, though).

> 3. ... should I output data-parent-fit='width' as a default, when neither cover nor contain is desired?

You can, but you can also leave the data-parent-fit empty or removed it entirely in this case, because the ``img`` width is identical to the container width in this case. Lazysizes will always get the right value here.

**Comment by lunelson** [comment]
Thanks for all of these answers @aFarkas. I'm still having some trouble with Safari and iOS Safari, which I'm guessing has to do with the `picture` element that gets wrapped around the `img`. Do you have some rules as to how the CSS must be (or not be), so that the `parent-fit='cover'` attribute—for example—finds the correct parent? Should the `picture' element maybe just be set to `height` and `width` of zero, so that the script will look at the next container?

**Comment by aFarkas** [comment]
@lunelson 
Actually I don't count `picture` as the parent element. I jump right over it. If you can give a test case I can look into it. (fiddle or codepen).

**Comment by lunelson** [comment]
OK I will try to isolate a test case; but I think you might be able to tell what's happening if you would take a quick look at this page: https://state-proto-rcb.surge.sh/view/chor/menschen/

In browsers other than desktop Safari, the `parent-fit` logic is working and pictures not only load the correct source they stay in correct scale-relation to their containers when I resize the window; in Safari however, when I resize from a large window (greater than 1200 or so) to a smaller one, the pictures do not scale down and remain too big relative to their containers.

Moreover in mobile Safari, all the pictures load in this 'too big' state to begin with, and then *still* continue to increase in size on scroll, presumably because it is triggering a `resize` event as you described.

I'm guessing it's something in my CSS that is disturbing the logic here but I can't see what

**Comment by aFarkas** [comment]
@lunelson 

I have looked into this. The `size` still can't be calculated, because `width` is set explicitly to `"auto"`. I understand that you need to do this to generate the effect, but without native intrinsic sizing support this can't work.

I would suggest that you try to use the bgset plugin. Here is [an example](https://jsfiddle.net/vzhLt3ub/1/):

```html
<style>
	.module-part {
		width: 25%;
		max-width: 400px;
		min-width: 200px;
	}

	.hold--cover {
		background-size: cover;
		padding-bottom: 100%;
	}

	.clip--circle {
		border-radius: 50%;
	}
</style>
<script src="https://cdn.jsdelivr.net/g/lazysizes@1.5.0-rc3(lazysizes.min.js+plugins/bgset/ls.bgset.min.js+plugins/respimg/ls.respimg.min.js+plugins/parent-fit/ls.parent-fit.min.js)"></script>

<div class="module-part mensch-image">
	<div role="image" aria-label="image alt name" class="hold--1-1 hold--cover clip--circle lazyload" data-bgset="https://state-proto-rcb.surge.sh/assets/images/samples/mitglied/lj-0160.jpg 144h 160w, https://state-proto-rcb.surge.sh/assets/images/samples/mitglied/lj-0226.jpg 203h 226w, https://state-proto-rcb.surge.sh/assets/images/samples/mitglied/lj-0320.jpg 287h 320w" data-sizes="auto"></div>
</div>
```

If semantic is important to you, you can add `role` and `aria-label` attributes.

**Comment by lunelson** [comment]
Thanks for looking in to that @aFarkas; but I'm still a bit confused. If I understand correctly, when you say:

> without native intrinsic sizing support this can't work

... you are talking about Safari? I thought the `parent-fit` plugin *was* for fitting in cases of intrinsic sizing, and it does seem to do that in every browser *except* Safari. Moreover, in Safari's inspector  the `sizes` attribute is correct, it's just the image is still not fitting consistently to its parent. 

In the meantime I made an alternate solution by marking the container as `--tall` or `--wide` (depending on its aspect ratio), and adding some CSS for these classes, so the contained image could have an explicit `width` or `height`—but again: this is precisely what I thought the `parent-fit` logic was supposed to handle automatically (?)

Demo of my interim solution:

http://s.codepen.io/lunelson/debug/jqWdKp

**Comment by lunelson** [comment]
Please note, the "fix" above really is not a fix. It works only in this simplistic case where the source image is square (so it's easy to know if the aspect of the container is greater or less than that of the image), and won't work at all for a container with fluid width/height.

**Comment by lunelson** [comment]
Also: I tried implementing it with `bgset` as you suggested. It works correctly in browsers other than Safari, but in Safari it chooses low-resolution sources (although the sizing is now right):

https://state-proto-rcb.surge.sh/test/bgset/

**Comment by aFarkas** [comment]
@lunelson 

I'm sorry, I will only have friday time to have a look into this.

From my view the latest link seems to work on Safari. I have a 2dpr macbook and it calculates a width of 190px and takes the 320px wide image (not the 226w image).

**Comment by lunelson** [comment]
@aFarkas Understood. I appreciate you taking the time to look in to this. My Safari troubles are on a standard-resolution (1dpr) screen, so maybe that's part of the puzzle

**Comment by lunelson** [comment]
With the latest version of this script and latest versions of Safari (macOS and iOS) the original problem (size attr changes on scroll/resize) seems solved. I'll post a new issue if the `bgset` thing comes up again
