### ISSUE TITLE
DOM batching / manual triggering measurements ?

### ISSUE THREAD

**Issue by lunelson** [aFarkas/lazysizes#256]
Trying to figure out from the docs, if there's a way to disable the automatic re-calculation of the `sizes` attribute (on resize, for example), and run it on a debounced resize or explicit call? Alternately, wondering if I can batch lazysizes measurements with a utility like [fastdom](https://github.com/wilsonpage/fastdom)?

**Comment by aFarkas** [comment]
Why? What Problems do you have? Do you have an example, which shows layout thrashing.

**Comment by lunelson** [comment]
I'd have to contrive an example. It's just something I'm thinking about in principle. I haven't noticed any problems with lazysizes performance but as I understand it lazysizes is re-measuring image containers on every resize event—is that right? There are certain scenarios where I could skip this, e.g. when I know image sizes are only going to change on horizontal breakpoint changes. Also just curious about the batching because I've got thrashing problems with other libraries that I'm thinking about refactoring to use fastdom

**Comment by aFarkas** [comment]
No it is throtteled with a technieque that is optimized for reads. 

You can remove the lazyautosizes class to stop reads but you should"t need to..

About Layout thrashing focus on the writes (all writes should happen in a rAF. You can do this vanilla or with fastdom.mutate.). If you do so you won't need to special case reads.

**Comment by aFarkas** [comment]
I'm always open to make lazysizes faster. I asked back, because lazysizes is currently the only lazyloader I know of that efficiently avoids layout thrashing.

If you find something concrete please report. But I'm struggling with adding new hooks and features without proven advantages. For example I know, that I can optimize some parts, but my tests show, that it isn't that big of a deal (and I don't want to make lazysizes core bigger). At the end I really don't know any other lazyloader, that does thing that efficiently.

About your other problem. As I said, I always would only concentrate on the DOM writes (mutates).

My little helper for this problem looks like this:

```js
/*
* returns a function, that is wrapped in a requestAnimationFrame. Useful to separate read from write.
* While all reads can happen where needed (but never inside a rAF) any DOM writes should happen inside a rAF.
* @param {function} fn - function that should be wrapped in a rAF
* @param {object} [options] - options
*   @param {object} [options.that] - the this context in which the function should be invoked (binds that to the function)
*   @param {object} [options.batch] - whether multiple calls to the function during one frame should be let through or should be throttled to the last call
*
*   example usage:
 class MyWidget {
     constructor(element){
         this.element = element;
         this.changeWidget = writeFn(this.changeWidget);

         this.checkWidget();
         //add resize events and do more useful things....
     }

     changeWidget(add){
        this.element.classList[add ? 'add' : 'remove']('is-large-widget');
     }

     checkWidget(){
        this.changeWidget(this.element.offsetWidth > 600);
     }
 }
*/

var writeFn = function(fn, options){
    var running, args, that;
    var batchStack = [];
    var run = function(){
        running = false;
        if(options.batch){
            while(batchStack.length){
                args = batchStack.shift();
                fn.apply(args[0], args[1]);
            }
        } else {
            fn.apply(that, args);
        }
    };

    if(!options){
        options = {};
    }

    return function(){
        args = arguments;
        that = options.that || this;
        if(options.batch){
            batchStack.push([that, args]);
        }

        if(!running){
            running = true;
            requestAnimationFrame(run);
        }
    };
};
```

**Comment by lunelson** [comment]
@aFarkas thanks very much for that! I will report back if I come across a concrete case. I don't doubt that lazysizes is highly efficient. My concern was whether it might hypothetically interact poorly with something else that is running measurements on `resize` or `scroll` events. i.e., two different libraries might each be independently batching their own reads and writes, but still cause thrashing between them: `lib a read, lib a write, lib b read, lib b write`. If libraries allowed a 'plug-in' way of integrating a global batch (such as fastdom) if available, it would avoid this potential problem. However it's purely hypothetical so far. Thanks again for sharing your insight and code

**Comment by aFarkas** [comment]
Of course, I can't guarantee, that I don't force layout, if a lib is mutating the DOM at a wrong point. but if DOM is mutated inside of a rAF, lazysizes will never force layout.

> My concern was whether it might hypothetically interact poorly with something else that is running measurements on resize or scroll events. i.e., two different libraries might each be independently batching their own reads and writes, but still cause thrashing between them: `lib a read, lib a write, lib b read, lib b write`.

This is what I was talking about the hole time. And you don't need a central plugin, that manages this. The goal is to separate all reads and writes across all scripts without the need to share a common library.

So here is the `fastdom.measure/mutate` - way:

Collect all reads and collect all writes and request an animation frame and then call all collected reads and after that call all collected writes.

As we know right after the animation frame, the browser calculates the layout and commit the frame. 

Try to visualize the frame time line of  what is happening in the frame here. Basically all reads and writes are moved (from the `scroll`event) to the latest point inside the frame before layout calculation and reads and writes are called without a gap right after another.

Now, the problem with this is. If another library (B) does mutate DOM/CSSOM either right away (which would be bad) or even inside a rAF (the right way), but its resize/scroll handler was bound before library A, it would mutate before the measure batch of library A is called. This is your problem.

If you think about it, the problem is self-inflicted by library A. It moves its measure batch inside the latest point of the frame (The chances that layout is dirty is getting higher and higher at this time).

Here is what is happening more visual:

Before optimization:
`scroll-eventhandler a: read, write, scroll-eventhandler b: read, write  ||| rAF || frame commit |`

After failed optimization:
`scroll-eventhandler a: batchReadWrite a, scroll-eventhandler b: batchReadWrite b  ||| rAF: read, write of A batch, read, write of B batch || frame commit | v sync |`

As you already know, optimization didn't work here.

-----

Here is a much simpler and more efficient way of separating reads from writes.

Simply collect just all writes and move them in to the animation frame.

If you visualize this: You got the scroll event of library A and it does it's layout reads, then library A schedules its writes with a rAF, after that library B also immediately reads layout and also schedules its writes in a rAF.

`scroll-eventhandler a: read, batchWrite a, scroll-eventhandler b: read, batchWrite b  ||| rAF: write of A batch, write of B batch || frame commit | v sync |`

With this approach there is a clean standard way of separating things, that need no additional library.

If all scripts would follow the following simple rule: **all reads should never be called in a rAF and all writes should always be called in a rAF** you will never have layout thrashing. 

And while this is a lot compared to the reality, the rule above is so much simpler and much more efficient (it does not conflict with animating libraries) than the fastdom way, that expect you to also collect all reads and additionally introduces the need that all libs in the world have to use the same instance of fastdom itself.

**Comment by lunelson** [comment]
@aFarkas okay! I get it now 😄  I wasn't aware of the anatomy of how `rAF`s are scheduled in the timeline of a frame. No other resource I've read on `rAF` puts it quite in this way (using rAF to collect all mutations)—or connects it to the layout thrashing problem in this way, although both are topics that are written about a lot. The fact that `rAF`s are the *last* thing to run in a given frame would seem to be actually the most important thing about them...
