### ISSUE TITLE
Dareboost Testing Fails - Showing Images are Loading Below the Fold

### ISSUE THREAD

**Issue by dalecarter** [aFarkas/lazysizes#284]
Hi there 

We implemented lazy sizes as our lazy loading solution which for the most part works great.  The test site using is  surfsailaustralia.gtp-icommerce.com.au/subcatDisplay/Windsurfing  . 

We run tests on code quality on dare-boost and often it complains that images are loading below the fold unnecessarily.  Previously we used lazy loading without this reported issue but upgraded to lazysizes.

We also tested your demo page http://afarkas.github.io/lazysizes/#examples  in the dareboost.com and this was the same issue reported by dareboost.

5 images (757kB) are loaded too early
Load images above the foldline first, that means all the images that are visible without any scroll of the page by the visitor.

Webpage and images

Images use to represent more than 60% of the total weight of webpages. By loading initially the only images that are visible without page scrolling, you’ll reduce bandwith consumption as for your server and your visitors. If an image has to display after any visitor’s action (as scrolling) , then you’d better load it on demand, when necessary (lazyloading).

How to set up lazyloading?

You can get informations concerning the features and plugins proposed by your page’s frameworks/CMS. You should find some easy-to-set solutions. Some Javascript libraries could help you to implement lazyloading too.

Our Settings are
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.loadMode = 1;
window.lazySizesConfig.expand = 300;

The question is, does the code need a settings tweak to pass the dareboost testing, or do you suspect it is a false positive in the testing.

Regards

Dale
[DareBoost_report_577535810cf2570b62b94a4f.pdf](https://github.com/aFarkas/lazysizes/files/341738/DareBoost_report_577535810cf2570b62b94a4f.pdf)

NOTE: The test was done using Google Chrome and it may be a browser specific issue.  The issue was also reported when tested in Galaxy S6 mode.

**Comment by aFarkas** [comment]
> The question is, does the code need a settings tweak to pass the dareboost testing, or do you suspect it is a false positive in the testing.

You can change it to pass the test, but I strongly recommend not to do this.

lazysizes has a more intelligent source loading mechanism than other lazyloader. 

In general: Only loading images that are in view, can cause usability problems for user with slow connection. Users don't want to see how images are loading while they scroll your website. Images should be loaded instantly for them. Most lazyloader have an `expand` option, where the developer can expand the view so that near the view images are also loaded. But this can be also problematic, because if in view images and near the view images are loaded at the same time, loading those invisible images might decrease performance.

lazysizes instead loads in view images with a high priority and near view images with a lower priority. You can see this on your own site mentioned above:

<img width="852" alt="img-waterfall" src="https://cloud.githubusercontent.com/assets/188254/16495627/9afcf148-3eee-11e6-8b3d-6f9518e551c7.png">


The first 6 images are not loaded by lazysizes every other images are loaded by lazysizes. My browser was showing the first 4 images and therefore lazysizes loaded those with a high priority, after onload lazysizes pre-loaded the next two rows (8 images), so that the user doesn't have to wait as soon as he/she starts to scroll.

**Comment by dalecarter** [comment]
HI Alexander

Thanks for the clarification on this one.

Much appreciated.

We have incorporated lazysizes into our ecom framework along with the img-src code and you have done a great job.

We upgraded from lazy loading as your code incorpates better image handling at different sizes.

Regards

Dale

**Comment by dalecarter** [comment]
Hi Alexander

Good news for me.  Dare boost agrees with your synopsis re lazysizes.

So that’s a big tick for you. : )

Regards

Dale
