### ISSUE TITLE
Breaks Safari 9.0.1 with picturefill

### ISSUE THREAD

**Issue by whatisjasongoldstein** [aFarkas/lazysizes#294]
Hi,

In Safari 9.0.1—which doesn't have native picture support—lazysizes doesn't work when `<picture>` is just a wrapper for an `img`.

http://codepen.io/whatisjasongoldstein/pen/jAdjVd

Changing `picture` to `div` works. Using it with sizes alongside the picture works. Using only picturefill without lazysizes works, and it worked in the old version (http://www.theatlantic.com/static/common/js/lazysizes.js — sorry, I'm not sure which version that is).

Any idea what's wrong? It doesn't throw any errors.

Thanks,
Jason

**Comment by aFarkas** [comment]
lazysizes doesn't do the `data-src` -> `src` transformation, if it finds a `picture` element or a `srcset` attribute, the browser doesn't support the `picture` element and a polyfill is used.

This is done because in those cases, normally the `src` attribute should be only used as a **fallback**  `src` and transforming this to `src` would in most cases produce a second download.

I could write code to detect that the `data-src` isn't used as a fallback `src`, but this would make lazysizes much bigger for a pattern that shouldn't be used.

You can fix this by adding the `data-src` with `data-srcset` or by adding a `source` element:

```html
<picture>
    <img class="lazyload" data-src="https://raw.githubusercontent.com/whatisjasongoldstein/buildcss/master/src/img/husky.jpg" data-srcset="https://raw.githubusercontent.com/whatisjasongoldstein/buildcss/master/src/img/husky.jpg">
</picture>

<picture>
    <source data-srcset="https://raw.githubusercontent.com/whatisjasongoldstein/buildcss/master/src/img/husky.jpg" />
    <img class="lazyload" data-src="https://raw.githubusercontent.com/whatisjasongoldstein/buildcss/master/src/img/husky.jpg">
</picture>
```

**Comment by aFarkas** [comment]
Another way would be to use the https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg plugin instead of picturefill, because there I try to detect those special not used as fallback cases.

**Comment by whatisjasongoldstein** [comment]
That makes sense. And since the image is being loaded with lazysizes anyway, there's no benefit to it being an `src` instead of an `srcset`. Thanks.
