### ISSUE TITLE
How to reload content using the include plugin?

### ISSUE THREAD

**Issue by dangayle** [aFarkas/lazysizes#313]
I'm making extensive use of the include plugin (love it), but I'm wondering what the best way to reload included content. Is there a js hook I'm missing?

**Comment by aFarkas** [comment]
You can re-start the plugin by simply re-adding the `class="lazyload"` (i.e.: `element.classList.add('lazyload')`).

Please close if this helps.

**Comment by dangayle** [comment]
Really? That will do it? Awesome.

**Comment by dangayle** [comment]
It appears to get stuck in the lazyloading state on Firefox: http://i.imgur.com/kJtyjw2.png

**Comment by dangayle** [comment]
You can see this on http://www.spokesman.com/, the big photo section right below the top headlines section. (BTW, our newspaper site uses lazysizes for everything)

**Comment by aFarkas** [comment]
I won't habe time to Look into this before sunday. I will then.

**Comment by aFarkas** [comment]
I forgot the API a little bit. This is by design, if you do not change the currently loaded URL the script won't do much because the content is already loaded.

You have three option:

1. Change the URL by adding a cache buster (might also be good in case the browser has already cached the answer).
2. Together with adding the `lazyload` class remove the `delte elem.lazyInclude` to make the plugin forget that it is already loaded.
3. Download the master version and use the new `lazySizesConfig.include.allowReload = true` option.

**Comment by dangayle** [comment]
Awesome. Thank you!

**Comment by kooshiel** [comment]
I'm confused as to how to use the `lazySizesConfig.include.allowReload = true` option. I've set this in the global config, but don't know how to put it to use. So far, I've tried adding a cache buster to the image URL and changing the class to `lazyload`, but lazysizes seems to still think that it has already loaded the image and thus the image is not reloaded. I didn't see this option listed in the documentation so perhaps I'm missing something.

I also don't know what you mean by: 

> remove the `delte elem.lazyInclude` to make the plugin forget that it is already loaded.
