### ISSUE TITLE
Demo page does not appear to be lazyloading

### ISSUE THREAD

**Issue by salcode** [aFarkas/lazysizes#33]
When I view the demo at http://afarkas.github.io/lazysizes/, it appears all of the images are loading on page load - not waiting for me to scroll down to the appropriate part of the page.

I've attached a shot of the Chrome Developer tools showing the images loading.

I'm using OS X 10.9.5 (Mavericks) with Chrome Version 39.0.2171.95 (64-bit).

![image](https://cloud.githubusercontent.com/assets/5194588/5561961/49b66ce0-8dcb-11e4-85c2-d9818eba7baa.png)

**Comment by yoavweiss** [comment]
@aFarkas - I've closed https://code.google.com/p/chromium/issues/detail?id=431862 since the behavior is as intended. If you'd change `sizes` in your example, or add resources such that the required resource would be larger than the one provided by `src`, I think  the example would work the way you want it to.

Let me know if you have any questions.
