### ISSUE TITLE
Is.bgset.min.js and Is.bgset.js not same version?

### ISSUE THREAD

**Issue by SuneRadich** [aFarkas/lazysizes#336]
As far as I can see, the minified version is updated in the RC2 commit, but the non-minified version has not been changed in 2 months?

Is this intentional until a final release?

Normally I always pull down the non-minified version of libraries, because I bundle up all files and minify myself. And to just prevent any longer build times and errors with minifying already minified files, and to work with code you can actually understand during development I would prefer to be able to use the non-minified file :)

**Comment by aFarkas** [comment]
@SuneRadich Everything is fine. The unminified version is the real source. If it isn't changed since 2 month it did not change. The minification always changes with the build step. If the core or another plugin changes all plugins are newly minified, even if they did not change.

I also use always the unminified source.
