### ISSUE TITLE
Any proof that lazysizes is SEO compatible ?

### ISSUE THREAD

**Issue by abarre** [aFarkas/lazysizes#340]
I would like to bring an experiment that shows that Google bot may or may not execute the javascript while crawling a page.
See the details here : https://www.stephanboyer.com/post/122/does-google-execute-javascript.

IMO, it means that the SEO compatibility is built on a wrong assumption on the fact that Google Bot always executes the JS. 
Let me know if I miss something on this point ?

**Comment by aFarkas** [comment]
How do you come to this conclusion? Your own test shows, that google executes JS. 

google uses multiple programs to scan the web (different kind of bots), with different possibilities. There are bots that are extrem fast, but can not handle JS. As soon as your site is found other bots with more features will crawl your site on a later time. A bot that can execute CSS and JS has to do a lot more and is therefore a lot slower, but it's results are more precise and therefore are most important for the google index, it only takes its time. (The experiment just shows this pattern. It would be a problem, if google switches from "Google executes JavaScript" to "Google does not execute JavaScript" at a later point but google doesn't.)

In case you have problems with that, you shouldn't use images at all, because - you guessed it - google has a special (also slower bot) to handle image content.

google has a simple feature for webdevelopers, that is called render as googlebot. You should use this and mostly relay on it.

**Comment by abarre** [comment]
Thank you @aFarkas for this extended explanation.
