### ISSUE TITLE
How can I make images on first screen not lazy load?

### ISSUE THREAD

**Issue by michael811** [aFarkas/lazysizes#356]
Please see title, thanks!

**Comment by sebssch** [comment]
are there any solutions?

**Comment by gety9** [comment]
Sorry for newbie question, what does 'first screen' mean?

**Comment by tomagladiator** [comment]
Do you meen : images Above the fold?
So visible without scrolling.

**Comment by kylescousin** [comment]
@tomagladiator I'm someone else, but I wanted to ask this too :)

Apparently all images are loaded at once, even the ones below the fold. I want them to start loading when the image comes in the visible area when scrolling.

Is this possible?

**Comment by aFarkas** [comment]
If you want to not lazyload an image simply use `src`/`srcset` instead of `data-src`/`data-srcset`. 

@kylescousin 
This is not really true. lazysizes has basically three loading stages. First lazysizes starts to only load images in view, soon after that lazysizes loads images very near to the fold and then (after onload) lazysizes starts to load images a little bit further to the fold.

Your user shouldn't wait to much for images to load, you know. But you can configure the behavior to your needs. Using `expand`, `expFactor` and `loadMode` options. Please simply RTFM this is why I wrote it.
