### ISSUE TITLE
Images are loaded twice

### ISSUE THREAD

**Issue by Gonzo2028** [aFarkas/lazysizes#377]
Hey, your code works awesome, except for a bug which will made me to sort it out again if not fixed.

I am having a picture element with two sources, one for jpeg and one for webp with various sizes (depending on the source image) along with a fallback <img src="" alt="" />  inside the picture and i combined your stuff with the swiper.js library.

As you can see in the chrome dev console (with disabled cache or with empty cache) it now loads the largest image, too. But in chrome it should load only the sizes-matching webp image.

Here you can see the code in action: https://mysexydate24.com/de-DE

**EDIT:** Ah: forgot to mention that you have to use the mobile dev option or a mobile useragent to see it!

Regards
Gonzo

**Comment by aFarkas** [comment]
>Ah: forgot to mention that you have to use the mobile dev option or a mobile useragent to see it!

And I thought you want to prank me first. Jenny aus Waldfeucht... ;-)

This is a bug in swiper.js. Swiper.js does obviously not support `picture` and the `srcset` code (that kicks in) has some flaws.

You can remove the error by swiper by turning it's corrupt feature off:

```js
preloadImages: false,
//not needed should be automatically false then, but helps
//updateOnImagesReady: false,
```

In case swiper has then problems to determinate the height of carousel items follow the instructions: https://github.com/aFarkas/lazysizes#updating-layout-of-js-widgets

I hope you can abstract/adjust the example code to your needs, otherwise just ask.

Please close if this helps.

**Comment by Gonzo2028** [comment]
Haha, you re welcome ;).
This page is serious, no doubts.

i changed the setting to preloadImages: false, but this does not fix it.
Any ideas?

**Comment by Gonzo2028** [comment]
Ah, that worked, something went wrong in my automatic optimization (minifiying, compression) algo.
Thanks man!

Now that page is really fast and awesome!
