### ISSUE TITLE
lazysizes and progressive image rendering

### ISSUE THREAD

**Issue by jschroeter** [aFarkas/lazysizes#40]
Alexander, thanks for sharing this great script, it works like a charm! We're looking for a solution for dynamic sizes for a long time.

I just stumbled upon one thing: when using the LQIP pattern, browsers (tested Chrome and FF) skip their nice Progressive JPG rendering. That means, the low quality image will stay visible until the high quality image is completely loaded. But actually at one (unknown) point during loading the high quality image, the progressive rendering would be better than the low quality version. I found a similar issue about [browsers skipping progressive rendering when the src attribute is being replaced](http://w3facility.org/question/progressive-jpeg-isnt-progressive-when-changing-image-src-dynamically/), this also seems to happen when browsers switch from src to srcset. Removing the src attribute before setting a new value/srcset helps. But of course the image would be gone for a few seconds.

I just prototyped a little hack which places the low quality src as background image on `lazybeforeunveil` and removes the src attribute. It seems to work well, have a look:

1. Image: original lazysizes with LQIP pattern
2. Image: lazysizes with LQIP pattern + background image hack
3. Image: native srcset with fixed sizes

Chrome: http://www.webpagetest.org/video/view.php?id=150118_d352f41d3adc756fe1334948b8f692aa693f079e
Firefox: http://www.webpagetest.org/video/view.php?id=150118_191a1951405f6c8e68a9c6695bd36544962adb46

Or try in your browser: http://schroetermedien.de/_temp/respo/

What do you think? Does this make sense? I mean actually this is something the browsers could fix, but I guess they won't fix it. It works well in our case with the low quality src, but e.g. imagine when replacing a 2x image with a 3x variant, rendering the new src progressively would cause a short unwanted loss of quality.

Thanks a lot,
Jakob

**Comment by aFarkas** [comment]
I like the idea especially because in general larger images should be compressed using progressive mode and yes I think this makes often sense. And your test demonstrates, that this is better than the normal lqip pattern.

Maybe you could also do a pure markup pattern for this:

```html
<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
    class="lazyload"
    style="background-image: url(image-0.7.jpg);"
    data-srcset="image-0.7.jpg 0.7x, image-1.jpg 1x, image-2.jpg 2x"
    alt="my image" />
```

But what is more important for me is the fact that you don't really care about my suggested patterns and try to alter them to your needs using the right API for this (i.e.: Don't think it's a hack). As I started with this project I only documented the lqip pattern and only because I saw that a lot of people are referring to it as kind of a holy grail, I changed the documentation to add other patterns. Sometimes this is best sometimes something else is better. So I don't want to give final rules. I simply wanted to give a tool to do lazyloading.

This said:
I find it a little bit surprising, that the normal source is loaded similar fast to the lqip source example, which means you can also try the simple pattern (i.e.: lazyloading but without an initial src). This doesn't give you any preload parser advantage but might also give a good result.

For the simple pattern you could also uitilize some classes:

```css
.lazyloading {
    background: #eee url(spinner.gif) no-repeat center;
}
```

Additionally I would test this with a "real" site, which has some more dom, script + css and so on. Also using webpagetest is the right thing todo ;-).

**Comment by jschroeter** [comment]
I already tried doing it with pure markup, but for progressive rendering the src attribute must be removed before setting srcset. I tried to completely remove the attribute in the markup but couldn't get rid of this broken image border. Any ideas?

I'll do some more testing and keep you updated.

**Comment by aFarkas** [comment]
Did you try to use a transparent image as the ``src``? This here is transparent: ``data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==``

**Comment by jschroeter** [comment]
Yes, but I still need to remove this `src` via JS on `lazybeforeunveil` to get the progressive rendering.

**Comment by aFarkas** [comment]
@jschroeter 
Sorry, my fault. You can't do it with pure markup. You already mentioned the reason for this in your first comment. So I wouldn't call your code a hack, pretty straightforward to me.

**Comment by jschroeter** [comment]
I decided to write a little plugin for that: https://github.com/rukzuk/lazysizes/tree/master/plugins/progressive
Still testing, seems to work well on Chrome for Windows and Chrome for Android. Firefox too, except it shows the broken image icon shortly after removing the `src`. I guess there is a little delay between `lazybeforeunveil ` gets called and respimage polyfills the `src` again. I already tried to remove the icon via `-moz-force-broken-image-icon` but without success.

**Comment by aFarkas** [comment]
About the broken image icon. You can test whether this can be fixed by moving [this code](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L364-L366) above the setTimeout.

If this help I might change this. But want to fix https://github.com/aFarkas/lazysizes/issues/42 before.

**Comment by jschroeter** [comment]
Thanks for the idea, but it doesn't help. I'm thinking about only enabling the plugin for browsers with native `window.HTMLPictureElement` support. Hopefully it will be supported by Firefox soon and I guess everything works fine then.

**Comment by aFarkas** [comment]
@jschroeter 
This is said. The information about FF respimg support are ambivalent. On the one hand there are pretty close on the other hand the main developer of the respimg implementation has left mozilla: https://github.com/ResponsiveImagesCG/newsletters/blob/master/RICG-newsletter-2015-01-09.md
