### ISSUE TITLE
images lazyload at same time

### ISSUE THREAD

**Issue by digisocialnet** [aFarkas/lazysizes#400]
I am trying to use lazysizes with Imgix.js and the <picture> element. All of the images lazyload immediately and I can't figure out why. Am I doing something wrong? [jake101.com](http://jake101.com)

**Comment by aFarkas** [comment]
Yes you are something wrong. The Imgix.js script already "reveals" all images. You need to either let this script transform to `data-srcset` attributes or do not run the Imgix.js script initially and hook into the `lazybeforeunveil` event and init this script there for each element.

Please read the documentation of both scripts.

**Comment by digisocialnet** [comment]
I've read both documentations many times. I took out imgix.js and created the URLs manually but it still loads everything at the same time. http://jake101.com/

**Comment by aFarkas** [comment]
> I took out imgix.js and created the URLs manually.

This seems like a legit solution maybe already the best.

> It seems to load a lot of images at once still...

Yes there are still 2 issues to solve (sorry). If you disable JS and inspect the `img.lazyload` elements you see that these have a width of 0 pixels. As a result of this all images are already in view at once (This is what lazySizes sees initially and therefore starts to download the first 10 images). The cause of this is that your images have a height of 100% and a width of auto. auto means here 0 before all images are loaded no matter how tall the layout is. This also causes another problem: The sizes attribute is calculated wrong. Because you need to provide a calculable width.
Here are 2-3 examples how to solve this issue: https://github.com/aFarkas/lazysizes#tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps

You can also solve this issue by adding a low resolution image as initial `src` attribute in this case the width is only calculated after the low src is downloaded by the browser.

By solving this problem you will see that much lesser images are downloaded and the sizes attribute is calculated the right way.

> ... it is hard to see it fade in, if at all

If you are doing this for the fade-in effect, you should consider to add an additional lazyload class to the wrapper element in conjunction with the data-expand attribute and to only use the css transition on this wrapper element. This will only work as soon as you have solved the first problem.

```html
<div class="cover-item lazyload" data-expand="-9">
    <img class="lazyload" ... />
</div> 
```

**Comment by digisocialnet** [comment]
Thank you for the help and for creating such useful software.

**Comment by blksmr** [comment]
Hi @aFarkas i'm getting the same issue on my website hiasmir.com
i don't understand why my all my images are loaded at same time and not on the viewport scroll can you explain me what i missed there ?
Ty
