### ISSUE TITLE
Lazysizes + CSS Multi Column Layout

### ISSUE THREAD

**Issue by rauberdaniel** [aFarkas/lazysizes#416]
I am trying to use Lazysizes together with a two-column css layout created by `column-count: 2`. This basically achieves a similar result to isotope (creates two independent columns so that the images stack on top of each other without a gap if there are unequal heights).

However, lazysizes doesn't appear to work correctly in this case. At some point, images will be loaded in a way that the columns shift and the first image in the second column might jump to the bottom of the first column. My images do all have the `width` and `height` predefined, so it should be possible to keep the spacing for them done perfectly and just insert the images on scrolling without layout shifting.

**Comment by aFarkas** [comment]
@rauberdaniel 

lazySizes does not do any layout changes. If you override your `width` and `height` attributes using `width: auto` and/or `height: auto` the browser will change the layout as soon as the images are loaded.

Otherwise I would need to see a testcase?

Please close if this helps or give me a testcase.

**Comment by rauberdaniel** [comment]
You are absolutely right, after checking again I noticed there were a few images missing the width and height attributes. I thought I had given it to all images but seems like I missed some. Sorry for the ticket, everything works fine 👍
