### ISSUE TITLE
`Size: auto` updates when browser shrinks, but not when it expands

### ISSUE THREAD

**Issue by dbchristopher** [aFarkas/lazysizes#433]
We've noticed a behavior where lazysize will update the `size=auto` setting when resizing the window, but only if shrinking the window. If you maximize the window again, the images will stay small.

**How to recreate:**

1. Load a page at any size
2. Shrink the window, and inspect an image. The `sizes` attribute has updated to reflect the new smaller size.
3. Expand the window, and the `sizes` attribute never updates.

**Expected behavior:**

Sizes attribute would update for both shrinking and maximizing window resize.

**Comment by aFarkas** [comment]
This is not true and proven by the official demo site. Please provide a testcase or close this issue.

**Comment by dbchristopher** [comment]
Thank you for the response @aFarkas. Here is a hacky "screencast" demonstrating the issue https://www.youtube.com/watch?v=iDfLC68J7Jg&feature=youtu.be

**Comment by aFarkas** [comment]
@dbchristopher 
I think you have a misconception of what auto sizes means. It is about transferring the defined CSS width of the image to the HTML `sizes` attribute, so that the browser can download the right image candidate.

The `sizes` attribute can only affect the layout width of an image, if there is no CSS width defined (which is the case in your video).

Your problem should be fixed with the following CSS:

```css
img {
    display: block;
    width: 100%;
}
```

Of course you might want to define the CSS width different, but you have to define the width. 

Another (in most cases less ideal) solution is to hook into the `lazybeforesizes` event and provide the width there.

**Comment by dotmagic** [comment]
@aFarkas I have the same issues. Yes, width 100% does fix it. But I can't use it since this images come from a large database with different dimensions.

So my CSS code for the image just set `max-height:100%; min-height:100%` and there's a wrapper with a equal 1:1 square size. All images are centered.

Can you confirm the only workaround for the scenario above is using your object-fit plugin? I would really prefer a CSS only solution.
