### ISSUE TITLE
To slow loading images

### ISSUE THREAD

**Issue by RobertGavick** [aFarkas/lazysizes#449]
Hello,

Could you tell me why the images are loading too slowly when scrolling down the page? Can we speed up that?
url: https://getpublii.com/themes/demo/qf/black-and-white-fashion-photography/

**Comment by alpipego** [comment]
It's a non-issue for me. They load fast enough that I don't even see the lower quality images (except a flash for the first one).

**Comment by aFarkas** [comment]
@RobertGavick 
I don't see your issue too. But you can either extend the `expand` option or you can update lazysizes and lower the `ricTimeout` option.

Note: Your version of lazysizes has a non configurable `ricTimeout` of `1000`. The newest lazysizes has `300`. (Lower is faster, but also increases the possibility of jank while scrolling.)

**Comment by dev-101** [comment]
@alpipego

I was 'annoyed' by slow scrolling update, which is noticeable in case of large images (of course, not with small thumbs and fast connection), and was confused at first how can we override the default behavior, because there is no conventional configuration, like in other libraries.

It is all documented, read documentation always (check project's home page or readme.md file)

I use this for good/better than default results, there are other parameters/ways, see docs, for example:
```
<script type="text/javascript">
lazySizesConfig.expand = 1000;
lazySizesConfig.expFactor = 3; // max 4
</script>
```


It will override viewport area and initiate/trigger elements loading earlier.
