### ISSUE TITLE
Data-size: auto calculates wrong sizes on Edge 

### ISSUE THREAD

**Issue by RobertGavick** [aFarkas/lazysizes#456]
Hi,
When browsing the following page https://getpublii.com/themes/demo/mercury/isotope/ on Edge browser you can notice that all the pictures have similar size and look like a grid. On the FF or Chrome, pictures have the right size and the layout looks like masonry.

image markup: 

```
<img data-sizes="auto" 
     src="{{urlXs}}"
     srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
     data-srcset="{{srcset.cards}}"	
     width="{{width}}"
     height="{{height}}"
     alt="{{alt}}"
     class="lazyload blur-up">
```
The example picture on the Chrome has a right size: 362px but on the Edge: 314px
Tested on the new Edge version that already supports object-fit.

I will be very grateful for any help.

**Comment by aFarkas** [comment]
@RobertGavick 
I can not really reproduce your error and I suspect, that your expectations are wrong.

The calculated `sizes` attribute depends on the layout width of your image and is calculated correctly in Chrome as on Edge. (It is only different because the window width was bigger in Chrome in your case.)

See the attached screenshot. There you see, that the layout width of your image is 433.5 pixel and the calculated width is correctly `434px` pixel.

<img width="933" alt="bildschirmfoto 2017-12-18 um 12 26 47" src="https://user-images.githubusercontent.com/188254/34104022-1c3b9d26-e3ef-11e7-8a6a-7e85a09cbe04.png">

-----

About object-fit. As soon as you don't use the value `fill` you must add a width and a height attribute other than `auto`. Which means in your case the `object-fit: cover` has no effect.

---

However as soon as you are using `object-fit` (with height and width CSS properties) the situation becomes a little bit more complicated, because the browser might show a clipped section of your image. 

To get lazysizes to calculate this correctly. You have to do the following things:

1. Add the parent-fit plugin
2. Add either the aspect-ratio via `data-aspectratio` attribute.
