### ISSUE TITLE
bgset data-aspectratio

### ISSUE THREAD

**Issue by CloudMax94** [aFarkas/lazysizes#464]
I previously used the h descriptor, but Picturefill doesn't apply to >= Edge 16 now that it supports srcset.
[And Edge is incapable of parsing the h descriptor, and treats the size as invalid](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/6733566/)

I figured I could use the data-aspectratio attribute instead as a simple solution since I'm using parent-fit.
But it seems like the bgset plugin doesn't actually pass down the attribute to the source element.
It would be great if the attribute was passed down so that it can be used as one might expect.

**Comment by aFarkas** [comment]
I can not provide a single `data-aspectratio` for a single `div` element, because the aspect-ratio has to be passed for each `source` element (there are multiple different ratios possible). 

It makes more sense to use the h descriptor and then to remove it in case edge is used.

Also note: That in most cases object-fit should be used instead of bgset. (There you don't have the described problem.)

**Comment by dnwhte** [comment]
@aFarkas, what about supporting an array of values in data-aspectratio that correspond to the various sources?

**Comment by aFarkas** [comment]
You can already use the h descriptor to do this. This is the standard way of doing it. To solve the issues with edge you can either use the [respimg polyfill](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/respimg) or if you use picturefill you can use the [h descriptor standalone fix](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/fix-edge-h-descriptor)
