### ISSUE TITLE
requestIdleCallback is unreliable on complex pages

### ISSUE THREAD

**Issue by driskell** [aFarkas/lazysizes#467]
Hi,

I updated from a very old version and noticed the new one no longer was loading elements when they came into view for at least several seconds. This is Chrome on OS X latest both at time of writing. Elements are contained in an overflow scroll element.

Doing some testing it seems to be if I remove majority of elements from the page and just have the overflow scroll element things are much better, and simplifying the elements inside that element make it fine. However, with everything on the page it takes up to a second after stopping the scroll for the images to populate and during scrolling absolutely nothing happens (previously it would populate as you scrolled.)

I did some tests using a simple script to register idle callbacks and monitor the delay and in some pages far exceeded the requested timeout.

For example, paste this code into developer console on Amazon here: https://www.amazon.co.uk/Certified-Refurbished-on-Amazon/b/ref=sv_gb_0?ie=UTF8&node=8362590031

Then scroll whilst it's running. During first parts of page load you see entries several seconds delayed. And then sometimes hugely delayed timeouts.

Problem is even `ricTimeout=0` doesn't seem to help as it seems even `setTimeout` calls get delayed. I'm guessing we either need to make it run inside the animation frame or the scroll event itself or battle trying to reduce the complexity of the page - but I fear it'll still be an issue on many older slower devices.

Seems Chrome is getting smarter at making timeouts and idle callbacks "non-critical" that can run whenever, but actually in our case the revealing of images is pretty critical to us.

```
function callback() {
  d++;
  console.log('CALLBACK DELAY', Date.now() - t[d]);
}
var c, d, t;
function queue() {
  c++;
  if (c > 10) {
    console.log('STOPPED');
    return;
  }
  t[c] = Date.now();
  window.requestIdleCallback(callback, {timeout: 300});
  setTimeout(queue, 250);
}
function start() {
  c = 0, d = 0, t = {};
  queue();
}
start();
```

**Comment by aFarkas** [comment]
@driskell 
I can not replicate your issue with my Chrome on Mac on the provided amazon page. 

However I know that there is a problem here. As Chrome implemented `requestIdleCallback` I was very surprised because the delay caused by rIC while scrolling was nearly always 0ms (on normal pages), although scrolling is a heavy task and I assumed `rIC` should kick in. Then around 6 month ago Chrome changed its rIC behavior in combination with mousewheel/trackpad scroll dramatically. In the way that rIC callbacks are mostly never called while scrolling. Which means that a throttle algorithm using rIC behaves more like a debouncing algorithm in conjunction with scroll events (which makes rIC useless as a throttle base for scroll event handlers).

The following issues are related to this:
- https://github.com/aFarkas/lazysizes/issues/449
- https://github.com/aFarkas/lazysizes/issues/434

Anyway your suggestion to call it always will heavily hurt performance and battery live time. Can you please test the following script  (and anyone else who is interested in this maybe: @judbd) and report back:
https://gist.github.com/aFarkas/f3ae9f7f9c40169851ebb0307d9c3e67

**Comment by driskell** [comment]
I actually attempted to replace the rIC and rely on just timeouts and animation frame, but even setTimeout gets delayed on the slowest of machines.

I have attempted on a much faster computer and yes it seems to work fine there. It heavily depends on the available resources on the machine and something in Chrome just starts delaying everything. I even managed to remove all timeouts and only do animation frame but then hit another issue - network requests are made but load callbacks are never called - so on a fairly slow machine with a relatively complex page I now know:

* requestIdleCallback is delayed beyond timeout
* setTimeout is delayed beyond timeout
* Events do not trigger from network

As for battery live and performance - my issue is the performance is already dead and that's why Chrome is trying so hard to help by deferring timeouts - and it's unfortunate that it makes lazy loading almost impossible. And a wonderfully full battery is no good if a user isn't seeing images.

I looked at those tickets you specified but they do not help because of the network issue and even load events getting knocked back.

I actually now realise that the best thing we can do is to increase `expand` so that we load in more images (short of giving up on lazy loading). That way the user only needs to stop scrolling once or twice on the page rather than every few images. On fast machines this makes lazy load almost invisible too. The idea being that if the browser is too short on resources to even handle lazy loading reliably we need to use idle time preciously in order to pull in as many images as possible to help the user experience when they scroll through, whilst still balancing the bandwidth carefully.

Maybe there's a way to automate this - in general performance and battery life are only part of the equation - one that also involves experience and usability - and there's a battle here to think about 👍  Maybe even our approach is already wrong from the get-go :smile:

Thanks for the response and ideas.

**Comment by driskell** [comment]
Another idea we had was infinite loading rather than lazy loading might be a better UX. As it triggers an expected wait and users I test with are forced to stop scrolling to wait (you can't scroll further). Where-as showing tiles already present with no image yet can allow scrolling to continue. One to ponder I think!
