### ISSUE TITLE
Lazyloading not working if slow connection with "bgset" plugin

### ISSUE THREAD

**Issue by aliziani** [aFarkas/lazysizes#489]
Hello,

I am investigating on the plugin "bgset"
If you go to the demo website for the plugin: http://jsfiddle.net/trixta/bfqqnosp/embedded/result/
with chrome browser, click "F12" to open the developer tools, go to "Network" tab and choose "Fast 3G".
Requests for the images are sent but even if the result is a success nothing is displayed...
Is there an other plugin to add to fix this ?
Is there a timeout somewhere that could explain that behavior ?

![image](https://user-images.githubusercontent.com/5922212/38299023-44b2fa02-37f9-11e8-9580-c305010700d6.png)

**Comment by pkamps** [comment]
I have similar issues, on a slow VPN connection, sometimes the lazyload bg image is not displaying.
In firefox private window I can reproduce the issue 100%. The image is on top of the page - so it gets loaded directly after page load (no scrolling required).
The image wrapper tag (div in my case) gets the CSS class 'lazyloaded' but the data-srcset attribute value is not copied to a 'srcset' attribute. That 'srcset' attribute does not exists.
I think there is some race-condition on slower network connections causing the issue.

**Comment by JamesSingleton** [comment]
Hi, @pkamps and @aliziani have you guys been able to figure this out? This happens for me on IE11 where the class says lazyloaded but there is no image.

**Comment by peterkeung** [comment]
We ended up rewriting code to not use background images :(

**Comment by JamesSingleton** [comment]
@peterkeung oh no! The only reason why I am using background images is that allowing CSS to do the magic vs requiring exact dimensions for everything single breakpoint since how our code works is you have to pass in a height and width in order to get an image back, it was too much of a hassle. It would be nice if this plugin played nice with IE11.

**Comment by peterkeung** [comment]
"requiring exact dimensions for every single breakpoint" -- exactly what we had to do!

**Comment by JamesSingleton** [comment]
Yea, that is not ideal... especially when mobile breakpoints aren't all the same nor desktop breakpoints!

**Comment by aFarkas** [comment]
@JamesSingleton 
Then you are simply using the wrong plugin. https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/object-fit

**Comment by JamesSingleton** [comment]
@aFarkas so object-fit will take an image that is 650x433 that is displayed in a div that is 350x350 and Google's audits won't complain about displaying the incorrect aspect ratio? Because that is what I was using bgset for.

**Comment by aFarkas** [comment]
It partially polyfills the  `object-fit` property for non-supporting browsers. So you can use `object-fit` directly for the `img` element. 

Just look the demo: https://jsfiddle.net/trixta/x2p17f31/

If you are also using `srcset` with `data-sizes="auto"` use additionally `parent-fit` so that the `sizes` is calculated according to your aspect ratio.

**Comment by aFarkas** [comment]
And about the bgset plugin. The demo isn't working as expected because the lorempixel server responds with a `Cache-Control: no-cache, no-store`. This is basically a server issue. The plugin also works with slow connections.
