### ISSUE TITLE
Stop loading carousel images not in view as of yet.

### ISSUE THREAD

**Issue by vishy93** [aFarkas/lazysizes#498]
Dear community,

I am attempting to integrate this plugin along with OwlCarousel2. But, I seem to be getting images loaded that are not yet in view. For example, if you view the pen I have put together [here](https://codepen.io/vishpatel93/full/gzzpjY/); you will see that in the carousel below: images 1-4 are in view (if viewed on a device with a width greater than 1000px, or 1-3 if 600px-999px or 2 if less than 600). Now, looking in the network panel of my 1364px wide chrome browser, I can see that images 1-5 are loaded when scrolled into view then little while after image 6 is also loaded strangely, even though I have not scrolled the carousel at all.

Is there a way to get lazysizes to only load whats in view rather than these further two images?

**Comment by aFarkas** [comment]
@vishy93 

This is a feature not a bug. lazysizes will load first only all images that are in view, than after a while will preload all images that are very near the view and after `onload` will preload image that are a little bit whiter out of view. 

This is the normal behavior, which is good for your users, so that they are able to see all images more instantly, without waiting.

You can however change this behavior using `expand`, `expFactor` and `hFac`. Although I wouldn't change them.

**Comment by vishy93** [comment]
aFarkas, I understand, but if used in carousels or such, wouldn't it be a waste of loading if user does not interact with the the carousel?

**Comment by aFarkas** [comment]
It would be always a waste if the user doesn't scroll to the image. But if you have performance concerns, there are none, because lazysizes sorts and queue the downloads accordingly.

You have to choose wether the user loads 2-4 images more (but later) and sees an image immediately or does not preload images and has to wait.

**Comment by vishy93** [comment]
aFarkas, ahh okay thats fair enough

**Comment by njy** [comment]
I'll start saying the lazysizes is just plain awesome, like, really awesome, so thank you for having created it.
Having said that, the "problem" here is not about perf, because queues and stuff, but about being able to not load 20 images in a 20 slide carousel without a reason. Think bandwidth usage and the likes.
Does this make sense or am I missing something here?

**Comment by vishy93** [comment]
njy I understand, I guess aFarkas does have a point with regards to usability and not making users wait. Maybe a happy medium would be limit how far out of view it will load them, so in my case instead of loading like images 5 and 6, it would load image 5 only.

**Comment by njy** [comment]
@vishy93 yeah absolutely, I did'n mean to **not** load next/prev slides at all :-)
In my opinion the logic for carousels should be exactly the same as the usual lazysizes logic for off-screen images: load the ones on screen first, the near ones second.

I'll try to make an example: let's say I have a page with 1 opening image, 1 opening carousel and other 19 images, 1 of them being just below the fold. Also, the carousel has 20 images in total, the first being immediately visible.
So 20 images in the carousel + 20 images "alone".
Now, lazysizes is smart enough to load immediately the first "alone" image, then the one "alone" below the fold, then stops and waits for scrolls (good) but at the same time it starts loading all the 20 images from the carousel (if I got it right, otherwise sorry for the misunderstanding on my side).
As you see there's a difference in how images are treated (alone or in a carousel) and - unless obviously there's a hard technical problem to solve - it would be nice to have the same behaviour.

To avoid users waiting I was thinking if it may be possible to load immediately the first image in the carousel, queue the second (and maybe the last in case of a looping carousel?) and delay the others for when the users change slides.

Does it make sense?

**Comment by vishy93** [comment]
njy makes sense.

**Comment by vishy93** [comment]
@aFarkas you stated 

> You can however change this behavior using expand, expFactor and hFac

However, I currently have:

        window.lazySizesConfig.expand = -2;
        window.lazySizesConfig.expFactor = 0.01;
        window.lazySizesConfig.hFac = -0.4;

but too great a hFac would break the loading in mobile I believe. Is there a way to dynamically set this depending on screen size?

**Comment by aFarkas** [comment]
Yes of course but `hFac` should be a positive value.

**Comment by vishy93** [comment]
@aFarkas yeah I changed expand to be 0. What would you recommend for ideal settings.
