### ISSUE TITLE
lazysizes-display-clone not being replaced in IE11?

### ISSUE THREAD

**Issue by tobiv** [aFarkas/lazysizes#501]
In IE11, I get `lazysizes-display-clone`s with the original `img class="lazyloaded"` set to `display:none`. Is this expected behaviour? Because the clone uses background images/base64(?), sometimes the images are not sized correctly and I only get tiny thumbnails.

```
<img class="lazysizes-display-clone lazyloaded" 
     style='background-position: center; 
            background-image: url("/uploads/ps-1324x916.jpg"); 
            background-repeat: no-repeat; background-size: cover;'
     src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
     data-src="">
<img class=" lazyloaded" 
     style="display: none;"
     src="/uploads/ps-1324x916.jpg" 
     data-src="/uploads/ps-1324x916.jpg" 
     data-parent-fit="cover" 
     data-parent-container="prev">
```

**Comment by aFarkas** [comment]
Yes this is the expected behavior. The clone is the polyfill fallback. Please check your CSS about your size problem.

If the size problem is done by lazysizes I will look into this. But I need a simplified test case.

**Comment by moritzbappert** [comment]
Hey @aFarkas,
we have this exact sizing problem in IE11 at https://www.nutricia-med.de – look at the bottom most teaser image for example. Any idea why this happens? Connected to the object-fit plugin?

**Comment by tobiv** [comment]
You need to specify image sizes because the fallback works with background images. I ended up using `vw`/`vh` units for "fluidity" and they work with IE11.

**Comment by moritzbappert** [comment]
@tobiv do you have a working example for me?

**Comment by aFarkas** [comment]
@moritzbappert 
I don't see the problem. I don't even see lazysizes in use on this page.

In general yes you need to always `width` and `height` to your `img` element.

**Comment by abercrave** [comment]
Hi @aFarkas,

Sorry to comment on a closed ticket, but I am having the same `display: none` issue with the tout images under GENUINE MAZDA PARTS on https://www.mazdausa.com/owners/parts in IE11 on Windows 8.1 and 10. I am using lazysizes v4.0.2 with the object-fit plugin and the images have height and width defined as 100%. I've run into the same issue on other components.

![screenshot 2018-06-13 15 25 08](https://user-images.githubusercontent.com/868841/41379230-b6097e9a-6f1e-11e8-9d7c-be24244f2579.png)

Can you tell me if this is a bug or due to misuse of the plugin?

Thanks very much in advance!

**Comment by aFarkas** [comment]
@abercrave 

I can't say for sure because I don't experience the bug. Here a screenshot of what I see:

<img width="1187" alt="bildschirmfoto 2018-06-14 um 06 29 53" src="https://user-images.githubusercontent.com/188254/41391721-a463b4d4-6f9c-11e8-9bf5-b24495e38158.png">

The `display: none` element is totally normal. I assume it is a CSS bug by your version of IE. Often IE needs a `position: relative; height: 100%` on all parent elements until the positioned parent comes, which has the real height.

Do this to ensure: Remove the plugin. Now object-fit should be failing but you can see wether IE got the height of the images right, if yes it is a bug of my plugin, if not it is a CSS issue.

**Comment by abercrave** [comment]
Thanks very much for the reply @aFarkas. I checked again today and wouldn't you know that it's working for me today as well...

It was as if Browserstack's browsers were hanging in an intermediate state right before the first `lazysizes-display-clone` image (with the base64 `background-image` style) is removed and the second `lazysizes-display-clone` image has its `display: none` style removed. All the images' heights and widths were correct as well, something I confirmed visually by setting a border on them.

Anyway, this appears to be one of those fun-to-debug intermittent issues or simply a fluke. I'll open a new issue with more information if it persists. Thanks again.
