### ISSUE TITLE
'How to' section should include how to use with a div background

### ISSUE THREAD

**Issue by ajayns** [aFarkas/lazysizes#546]
One of the very common ways of using images after `img` and `picture` tags are using a div with a CSS background-image. I'd like to know what's the optimal way of adding lazyload in that case, along with any configurations available. 

It'd be great if this could be noted in the first section itself so it's easily visible to people.

**Comment by aFarkas** [comment]
This is fully documented. Here is how you can built your own thing:
https://github.com/aFarkas/lazysizes#js-api---events

And then you can find also 2 plugins that are already using background-image. You only have to read the manual

Most of the time people want to use background-image instead of real images because they can use background-size. For those people I strongly advice to use real images in combination with object-fit (and the object-fit polyfill plugin).
