### ISSUE TITLE
IE11 version thumbnail image slowly viewed.

### ISSUE THREAD

**Issue by seoungilchoi** [aFarkas/lazysizes#549]
Hi. I use nk visual portfolio plugin in wordpress. 
When I use by IE 11 version browser,I find thumbnail some of images blank image. 
so I asked this issue nk development person. 
He said "this plugin image script this lazysizes. 
so, I ask this issue. 
(If use device PC Version Microsoft Internet Explorer 11, can check this issue.) 
chrome browser no issue. 
my url : http://bold-b.co.kr

can I solve this issue?
Please help. 

Thanks.

**Comment by aFarkas** [comment]
@seoungilchoi 
I can not replicate your issue. But I see that you are using another image related script there, which is only running if IE11 is used so it is much more likley that this script is causing your IE11 only issue.

It's the following script: https://github.com/bfred-it/object-fit-images

On the other hand:
lazySizes comes with its own very simple solution of object-fit images. If the author of your page would instead use the following plugin it should be fixed: 
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/object-fit

Due to the fact, that the CSS syntax is the same to the other object-fit polyfill he has to simply remove the other polyfill and switch it with the lazySizes plugin.
