### ISSUE TITLE
lazypreload not really working on hidden items

### ISSUE THREAD

**Issue by hecktarzuli** [aFarkas/lazysizes#554]
I have some top menu items that are hidden until you mouse-over the menu item.  I have loadMode = 1 and expFactor = 0 and the items aren't preloading.  I had assumed even hidden items marked with the lazypreload class would preload no matter what settings are anywhere.. this doesn't seem to be the case?  To get something kind-of working i've had to monkey with loadMode & expFactor which seems weird.   Am I missing something?

**Comment by aFarkas** [comment]
I assume you are using the autosizes feature on these elements?

If yes, this is impossible because JS has to know the size of those images before they are loaded. You can use visibility: hidden instead if you want.

Please close if this helps.

**Comment by hecktarzuli** [comment]
I'm just using loadMode = 1 or 2 and expFactor of 0..  That's it.  I'm not doing anything about sizing.

**Comment by aFarkas** [comment]
1. An `expFactor` value below or equal to `1` is quite stupid.
2. This should work. Please provide a testcase or url to the website. 

Here is my simplified testcase:
https://jsbin.com/laqohifezi/1/edit?html,output

**Comment by hecktarzuli** [comment]
1) hahaha, I just didn't want any expanding loading :)
2) https://tonneaucoversworld.com/ Category Dropdown, though this doesn't have preload class.. I was playing in dev.

**Comment by aFarkas** [comment]
1. expFactor is a factor. Which means the normal expand is multiplied with it. The normal expand is between 370-500 pixel. With your config: It is still 370-500, but if the browser is idling it is 0. This doesn't make any sense. You have a higher preloading if there is something going on than there is nothing going on. 1 would be at least the same but it is not really a good idea.
2. If you set `expFactor` to 1.1 it should work.

**Comment by hecktarzuli** [comment]
Our site is a Single Page App.  I want processing power and bandwidth to be available for other things down the loading pipeline.  When you hit the page, we hit a couple apis client-side.  I want those api hits, and their immediate resources (images/css/js) to be able to load what they need, especially things above the fold.   

So you are saying, yes, even if I have something set to lazypreload, somehow expFactor affects it.

**Comment by aFarkas** [comment]
You can argue that `expFactor` shouldn't have any impact on lazypreload, but internally lazypreload is only allowed if the browser is in preloading mode and with your configuration you are destroying this and it doesn't help you with performance either it is just a silly configuration.

lazySizes has basically 3 internal expand values:

1. "shrinkedExpand": This is normally active to start downloads of only in view images. The shrinkedExpand is fixed to `0`.
2. "normalExpand": This is by default between 370 - 500 depending on the viewport of the browser and can be directly changed by changing the `expand` option.
3. "preloadExpand": This expand is used if there are no current downloads going on, the user is not scrolling and the document is complete. The value is calculated by multiplying the `expand` option with the `expFactor`. (This means if you would like to entirely disable this feature you would set it to 1. But setting it something below 1 is absolut silly.)

Now with your configuration you don't really help yourself, because you still say that lazysizes should preload images between 370 -500, but then you say if lazysizes thinks that the browser is idling - which means lazysizes could load even more images without hurting - you suddenly say the expand should be 0. This doesn't make any sense. 

If you want to make a good configuration for your use case do the following.

Leave `expand` and `expFactor` alone and then call the following function every time your router starts a new view:

```js
let timer;
export default function delayLazyPreloading(loadMode = 1){
    lazySizesConfig.loadMode = loadMode;
    clearTimeout(timer);
    timer = setTimeout(() => {
        lazySizesConfig.loadMode = 3;
    }, 1000);
}
```

Also Note: If your router starts a new view I expect that it has to wait until at least the component data and render logic has to loaded before an image that can be lazy (pre)loaded is rendered therefore it is in most cases not really necessary. Also as long as lazySizes loadMode is below 3 the browser won't lazypreload anything.
