### ISSUE TITLE
Additional Documentation for "The noscript pattern"

### ISSUE THREAD

**Issue by ohlr** [aFarkas/lazysizes#560]
In the readme.md could you add explanation about no-js ?

The code only works if the user puts `<html class="no-js">` and adds
```
<script>
  document.documentElement.className = document.documentElement.className.replace('no-js', 'js');
</script>
```

**Comment by aFarkas** [comment]
But this is not true.

**Comment by ohlr** [comment]
Okay, If I don't have that additional code on my page, I am seeing the alt tags from the lazyloading images above the noscript images given that js is disabled - I don't think that this is the desired behaviour

**Comment by aFarkas** [comment]
I think that has something to do with your special setup and not with lazysizes. Check your CSS

**Comment by naavis** [comment]
As far as I can tell, @ohlr is correct. The `.no-js` class name is not applied to anything when Javascript is disabled.

**Comment by aFarkas** [comment]
@naavis 
Writing readme is really an art and I'm not able to master it. There are things that you don't have to explain because developers should know that or at least understand it.

The pattern above is taken from the [html5 boilerplate](https://github.com/h5bp/html5-boilerplate) or at least made extremely popular by it. Every developer should either already know this pattern or recognize it by simply reading it. 

The fact that neither @ohl nor you knew it is sad, but you immediately understood that the author has to write it down.

Additionally my examples never state you have to do it this way or that way. It is simply an example how you can write JS/No-JS state classes. But there are x ways to do it. And nowadays you would write something like: `html:not(.js)`/`html.js` instead.
