### ISSUE TITLE
Integrate with focus point

### ISSUE THREAD

**Issue by yellow1912** [aFarkas/lazysizes#563]
Normally for responsive image there is the idea of using focus point to smartly crop the image without hiding the most important point on the image.

Some idea:

https://support.squarespace.com/hc/en-us/articles/205826028-Using-focal-points-to-center-images
https://29a.ch/sandbox/2014/smartcrop/examples/testbed.html

I wonder if this somehow can also work with lazysizes, or perhaps the images should be pre-processed and the focus point should be taken into account somehow during the pre-process?

Edit: Perhaps what I can also do is to let the lazysizes runs independently to render an image that best fits the desired size, then apply a "viewport" on top of it and with some smart use of overflow and transform i can shift the image around to best focus.

**Comment by aFarkas** [comment]
There is a difference wether you do it server or client side. It is much better to do it server side. In this case lazySizes is able to also calculate the right `sizes` attribute for you in case you use the `data-sizes="auto"` feature.

In case you do it client side lazyloading is possible but calculating the `sizes` attribute 100% correctly will probably fail.

To only do the lazyloading you can hook in either after the transformation to a "normal" image is done or at least if the image has loaded.

For the transformation we don't really have an event but you can use a helper like this:

```js
const wait = Promise.resolve();

document.addEventListenr('lazybeforeunveil', ({currentTarget} => {
    wait.then(() => {
        //do your image focal thing
    });
});
```

**Comment by dhymik** [comment]
I have the same issue. I have a large hero image on the landing page, which is changing in size and also in aspect ratio when the user resizes the browser window. This is why I need client-side focal point adjustment. I am loading the image with the original aspect ratio server-side.

@aFarkas It seems that I need `img { height: 100%; width: 100%; }` on the image for lazysizes to work. If I delete this css, then the image scales smaller with the browser window getting smaller, but it doesn't scale back up when the browser window is made larger.

But in order to do a client-side transform on the image to move it around, I need to render the image without `img { height: 100%; width: 100%; }`.

Would you have a suggestion on this?

@yellow1912 did you find a good working solution for this yet? I would be interested in seeing how you got this working.
