### ISSUE TITLE
When src present in IE11 images will not appear

### ISSUE THREAD

**Issue by awgul** [aFarkas/lazysizes#566]
Hey,

I put into `src` empty SVG with width and height like this:
`data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20width%3D%27960%27%20height%3D%27250%27%20style%3D%27background%3Atransparent%27%2F%3E`
and so it is later responsive.

I set `data-src` with image and `data-srcset` only with a 2x image.
But when I provide `data-srcset` with 1x and 2x image it is fine.
But I'd prefer not to reproduce the 1x iamge from `data-src`, shouldn't in IE11 get it from the `data-src` in first place?

On IE11 when I do it the class changes from `lazyload` to `lazyloading` and no images appear.

**Comment by aFarkas** [comment]
Yes, it should can you please provide an example so I can see the problem. You can use codepen, jsbin etc.. It is really easy to setup.

**Comment by awgul** [comment]
Hey,
I made a test and your library works.
But I have attached HTMLPictureElement from polyfill.io and then it doesn't work.
I use this for some other code.

You can have a check if you want to:
https://jsbin.com/jacetecula/1/edit?html,output

I think I'd need to try some other polyfill.

**Comment by aFarkas** [comment]
@awgul 

I'm not sure wether I can reproduce your issue. In your testcase I see that the 2x image is loaded in IE11 which is what I expect.

If this is your issue and you want to see only the 1x to be loaded you have to change your markup.

Either you should add all image candidates to the `srcset` and repeat the 1x candidate in the `data-src` or just remove the `src` attribute entirely. Another possible option is to simply do not use a polyfill then `src` is overwritten by `data-src` automatically.

This is by design: If you have a browser without responsive image support but you have a `data-srcset` and `data-src` and a polyfill lazysizes will not transform the `data-src` because this could lead to double downloads of 2 images (first the image from `data-src`-> `src` second the candidate that is chosen by the plugin.

Please close if this helps.

**Comment by awgul** [comment]
OK.
Thanks.
