### ISSUE TITLE
question : why removing src blank (gif pixel)

### ISSUE THREAD

**Issue by abarre** [aFarkas/lazysizes#594]
I see that a [commit](https://github.com/aFarkas/lazysizes/commit/1e115d024b2754b6402108d43cca7e6935388ad3) remove blank src in the readme and build. However, I didn't find an associated issue or a rational about this change.

Does blank src become obsolete for preventing the broken image icon on modern browser ?

**Comment by aFarkas** [comment]
This is a little bit more complicated. So not providing a `src` element.

Downsides:

1. Not valid markup
2. Broken image problem (in some browsers)
3. Under some circumstances the following bug: https://bugs.chromium.org/p/chromium/issues/detail?id=478153

Upsides:

1. Enables handling of progressive images
2. Faster image swap even of non progressive images (don't ask me why)

Handling of downsides:

1. Invalid: If you care use blank images
2. Broken: If you care use `.lazyload { opacity: 0.0001 }`
3. This bug was marked as won't fix, but was actually fixed between April 2017 and April 2018. 

At the end: Decide how you want to deal with the situation yourself.
