### ISSUE TITLE
lazysizes.min.js missing from 4.1.6 npm package

### ISSUE THREAD

**Issue by DickSmith** [aFarkas/lazysizes#597]
`lazysizes.min.js` and `lazysizes-umd.min.js` missing from 4.1.6 npm package.

**Comment by nternetinspired** [comment]
Still an issue in 4.1.7.

Maybe the docs should be updated @aFarkas? Docs refer to importing the .min.js versions which no longer exist in installed node_modules since *.min.js was ignored with https://github.com/aFarkas/lazysizes/commit/03bfca770beb6781bd5f5c09490119a367466d69

**Comment by aFarkas** [comment]
Sorry, for the inconvenience. The main problem why I have removed them is because if you `import`/`require` the `lazysizes.min.js` and then `import`/`require` any plugin the unminified file will be automatically also included by the plugin.

So for me a more clear doc would be the best known solution or do you have any ideas to solve this properly? About current docs I only see that I mention to include the `<script src="lazysizes.min.js"></script>`, but my understanding is that this is for the "old school users" as soon as you use npm `import lazysizes`; does the trick. Maybe I just add an `import` example, which also includes an optional plugin?

**Comment by nternetinspired** [comment]
No need to apologize and thank you for responding! I think that would be a great addition as I think application bundlers are pretty widely used now and set to be more so in future.

I'm using Webpack and importing like this:
```
import( /* webpackChunkName: "lazysizes" */ 'lazysizes');
import( /* webpackChunkName: "lazysizes-bgset" */ 'lazysizes/plugins/bgset/ls.bgset' );
import( /* webpackChunkName: "lazysizes-parentfit" */ 'lazysizes/plugins/parent-fit/ls.parent-fit' );

if ( !window.HTMLPictureElement || document.msElementsFromPoint ) {
  import( /* webpackChunkName: "lazyszies-polyfill-ie" */ 'lazysizes/plugins/respimg/ls.respimg' );
}
```
I was previously importing the .min versions, which is why my build broke on updating, but given that Webpack is minifying assets anyways that really makes no sense anymore, as you rightly said.
