### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by JonWallsten** [aFarkas/lazysizes#60]
Another "issue"/feature request is that as it is right now, you need to apply the settings before you add the script source, otherwise it will self initialize before you have the change to set init to false.
You have a 0 delay on the init itself if I'm not mistaken, men then it's to late. What about also wrap the init check in that delay? It messes up my structure that I have to put it in a special order instead in order to remove the auto init. Not a big deal, but might be worth thinking about.
Otherwise everything works great! Thanks!

**Comment by aFarkas** [comment]
As I wrote this line, this  caveat was clear to me... 

But you are combining your scripts into one script? Actually I'm not totally happy with anything about init/autoinit.

In general I want lazySizes to work similiar like normal webcomponents work. So in most cases you should not need to use ``init = false;`` .

**Comment by JonWallsten** [comment]
I'm am combining yes!
BUT, lets say include the script lite this:
``1: <script src="lazysizes.js" />
``2: window.lazySizesConfig = {
``3: init : false
``4: }
In this case, the auto init has already begun and will skip my setting.
And I always add vendor scripts first. Thats where the conflict is.

The reason I need to init the script myself is that I wanna make sure the $('img').on('load'...); is attached before initiating the script. Otherwise I get trouble with cached images being fetched so fast the event is attached after the images is loaded.

This results in a case where some of the images is hidden behind an overlay I keep above them untill the image is completely loaded(to not show the content in front of the image against the page's background).

**Comment by aFarkas** [comment]
It is a good thing to move the condition inside the setTimeout, so I will do this. Remember that you should also use the settings the following way, otherwise you might not get the intended result:

```js
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig.init = false;
```

But I think you have better options than this. In general it is a really good thing that [layzsSizes starts as soon as possible](https://github.com/aFarkas/lazysizes#tip-wherehow-to-include-lazysizes).

Here are some other options:

1. Pure CSS
lazySizes uses the classes lazyload, lazyloading, lazyloaded. You might be able to use only those to support what you need either by using z-index or by using the background property of your image.

2. Captured event delegation

Instead of querying for your images inside a domready event and initializing lazySizes after that. You can combine event capturing with event delegation and initialize lazySizes before domready.
```js
document.addEventListener('load', function(e){
    $(e.target)
        .filter('.my-image')
        .each(myAction)
    ;
}, true);
```
3. Use lazyloaded class in combination with load event
```js
$('.my-image')
    .one('load.myloadnamespace', myAction)
    .filter('.lazyloaded')
    .trigger('load.myloadnamespace')
;
```
4. Use load event in conjunction with complete property
This would be the pure native way...
