### ISSUE TITLE
Do I need parent-fit plugin if I don't use data-sizes="auto" but I use object-fit polyfill?

### ISSUE THREAD

**Issue by wujekbogdan** [aFarkas/lazysizes#612]
The documentation says:

> Include lazysizes and lazysizes object fit and optionally lazysizes parent-fit and lazysizes respimg plugin. Lazysizes object-fit and respimg plugin are only needed in browser that don't support object fit or responsive images. Lazysizes parent-fit is recommended if you use object fit responsive images in combination with data-sizes="auto".

But another part of the documentation says:

> The parent fit plugin extends the data-sizes="auto" feature to also calculate the right sizes for object-fit: contain|cover image elements and other height ( and width) constrained image elements in general.

So the more I read the more confused I am.

I'm refactoring an existing code where I already have sizes attributes. So it seems that I don't need to use `data-sizes="auto"`, so I don't need the parent-fit plugin. 

But on the other hand, I use object-fit polyfill for older browsers. The second quote indicates that parent-fit is required by the object-fit plugin.

So, will object-fit polyfill work properly without the parent-fit plugin?

**Comment by aFarkas** [comment]
Both paragraphs are clear. The second paragraph doesn't even mention the polyfill. You only need parent-fit if you use the CSS property `object-fit` in conjunction with `data-sizes="auto"`.

object-fit polyfill will also work without `parent-fit`.

But I assume that your own `sizes` attributes are not correct.

**Comment by wujekbogdan** [comment]
Thanks for the clarification.

> But I assume that your own sizes attributes are not correct.

Why?

**Comment by aFarkas** [comment]
Normally the sizes attribute reflects the layout width of an image. Which means the following CSS `img {width: 100px}` results in `sizes="100px"` of course with responsive images it gets more complicated. But as soon as you use `object-fit` it gets even more complicated because you have to factor in that your image might be cropped. If your image is cropped in width you have to add the cropped portion into the `sizes` calculation, which might result into `sizes="120px"` for the above example. If you use `contain` and there are blank spaces in width the `sizes` attribute might get smaller in those cases.

**Comment by wujekbogdan** [comment]
@aFarkas 
Interesting observation, thanks for the explanation.

**Comment by aFarkas** [comment]
@wujekbogdan 

You can see this in action on the last image in this [demo](https://jsfiddle.net/trixta/x2p17f31/). The `sizes` attribute is 2x bigger than actual display size.
