### ISSUE TITLE
Duplicate event handler for 'scroll' event?

### ISSUE THREAD

**Issue by collinsethans** [aFarkas/lazysizes#618]
https://github.com/aFarkas/lazysizes/blob/27ff2adf5ba6548297f252115744e1ef49ba4af9/src/lazysizes-core.js#L574

The 'onload()' already attaches afterScroll() to 'scroll' event which calls throttledCheckElements(). So this code in link above may not be necessary, just curious if there is a reason behind it.

Found this when we noticed that checkElements() getting called 3 times on every scroll, commenting it brings it back to 1.

**Comment by aFarkas** [comment]
@collinsethans 
Yes there is a reason behind it. As you see the `afterScroll` is debounced, which means that `checkElements` will be called another time with a different configuration as soon as scrolling stops. 

> Found this when we noticed that checkElements() getting called 3 times on every scroll, commenting it brings it back to 1.

This would be normally a bug.

All calls are calling `throttledCheckElements` and not `checkElements`, which makes it quite impossible that `checkElements` is called multiple times during a scroll. Of course there might be a specific scroll input type where `checkElements` is called twice for one scroll but this would be a rare situation and it is still throttled hence delayed by 100-130ms.

A normal scroll pattern looks like this:
<img width="1117" alt="Bildschirmfoto 2019-03-20 um 07 07 53" src="https://user-images.githubusercontent.com/188254/54663074-68081280-4ae0-11e9-9fd1-4d9b540eedda.png">

If you "smooth" scroll there are 8 `scroll` events between each `checkElements` calls as soon as it gets slower there are then 7 and then 2. During this time after scroll is never executed at the end it is and therefore `checkElements` is called another time. But this is happening throttled about 125ms later.

So if there are really 3 `checkElements` calls on normal scrolls. Then this is clearly a bug. But I doubt it. I assume it is a misinterpretation because `checkElements` is called by a lot of things.
