### ISSUE TITLE
Consider adaptions to lazysizes for the upcoming native lazyload browser feature

### ISSUE THREAD

**Issue by thasmo** [aFarkas/lazysizes#629]
See [this article](https://addyosmani.com/blog/lazy-loading/) for a brief explanation of the new `loading` attribute coming to Chrome 75, supporting `img` and `iframe` elements.

`lazysizes` may needs adaption to play nicely with the new browser feature in the future.

**Comment by thasmo** [comment]
For example, it would be nice if `lazysizes` could swap relevant `data` attributes to the actual attributes or, at least, provide a public API method to do so.

**Comment by aFarkas** [comment]
Yes, I can provide such a plugin. If you want you can already do so by using the following method `lazySizes.loader.unveil(DOMNode)`:

```js
import lazySizes from 'lazysizes';

if ('loading' in HTMLImageElement.prototype) {
	const images = document.querySelectorAll('img.lazyload[loading], iframe.lazyload[loading]');

	images.forEach(lazySizes.loader.unveil);
}
```

My plugin would include maybe some options for example to fully disable lazySizes and detect new images.

But keep in mind due to the fact that JS has to still alter the DOM before anything gets loaded one interesting aspect of lazyloading is not supported: LazyLoading initially in view image after CSS is loaded but before JS is loaded which means loading lazysizes still has a high priority.

It would be interesting to already see some heuristics in the lazyloader already in the preload parser. For example under some circumstances load the first 3 images instantly before even CSS is loaded. From my understanding often the backend doesn't distinguish between images that are always "above the fold" and images that don't....

Btw.: As soon as the browser waits to load images until styles are loaded the browser will also be able to implement the `data-sizes="auto"` feature for those images (request it!!!).

**Comment by aFarkas** [comment]
From your article:

> Not specifying the attribute at all will have the same impact as setting `loading=auto`.

Interesting: I guess this idea will break expectations of some website authors. As soon as browsers start to consider to match `auto` to `lazy` under some circumstances.

**Comment by aFarkas** [comment]
Do you guys have any suggestion for the configuration option that disables listener events. My current idea is `disableListenerOnNativeSupport` which is quite long and ugly.

**Comment by aFarkas** [comment]
Did anyone off you already tested the plugin with the newest Chrome canary? It seems to work pretty well. In case you don't want to change your markup you can simply set `nativeLoading.setLoadingAttribute = true`. In case you don't use lazySizes on any other elements than `img` and you aren't using `data-sizes="auto"` on `img` that are hidden using `display: none` you can also set `nativeLoading.disableListeners = true`

**Comment by aFarkas** [comment]
Here you got the final plugin:
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/native-loading

**Comment by housseindjirdeh** [comment]
@aFarkas final plugin looks amazing 👍 

I'm curious if you've thought of updating the plugin to purely rely on the `loading="lazy"` attribute?Using `setLoadingAttribute` to update all images to have the `loading` attribute makes sense for folks who are already relying on lazysizes and don't want to change their markup to support native lazyloading, but I think it might be useful to also provide developers who end up using `loading="lazy"` an easier way to polyfill for other browsers by falling back to this plugin/lib

CC @addyosmani @mathiasbynens

**Comment by aFarkas** [comment]
@housseindjirdeh 

Not sure wether I understand you right here. Do you mean that developer should be able to use `loading="true"` in combination with the normal `src`/`srcset` attributes and a plugin will then transform this to `class="lazyload"` and `data-src`/`data-srcset`?

**Comment by housseindjirdeh** [comment]
@aFarkas that would be the ideal scenario, but not sure if it would be possible to transform `src/srcset` attrs to `data-src/data-srcset` before the page gets instantiated? I was referring to at least allowing developers to use `loading="lazy"` along with `data-src/data-srcset` without needing to specify `class="lazyload"`

**Comment by aFarkas** [comment]
> but not sure if it would be possible to transform src/srcset attrs to data-src/data-srcset before the page gets instantiated?

In theory it is not possible. In practice it might work quite good under specific circumstances - at least in IE and FF. Safari is for me the big question. But for me it is too early to do such a kind of "real" polyfill. And of course most other plugins and lazysizes features - especially `data-sizes="auto"` won't work anymore.

> I was referring to at least allowing developers to use loading="lazy" along with data-src/data-srcset without needing to specify class="lazyload".

I don't really see much benefit in it for the developer. How would you advertise it? Hey developer you only have to change the HTML partially. As soon as a developer has to change `src`/`srcset` it is not much of work to also add a class.

If you think that is useful for you, you can still write the following JS code (not tested) to do it yourself:

```js
const throttledTransform = (() => {
	let runs = false;
	const { cfg } = lazySizes;
	const selector = `img[loading="lazy"]:not(.${cfg.loadedClass}):not(.${cfg.lazyClass}):not(.${cfg.loadingClass})`;
	const transform = () => {
		document.querySelectorAll(selector).forEach((node) => {
			node.classList.add(cfg.lazyClass);
		});
		runs = false;
	};

	return () => {
		if (!runs && document.querySelector(selector)) {
			runs = true;
			lazySizes.rAF(transform);
		}
	};
})();
new MutationObserver( throttledTransform ).observe( document.body, {childList: true, subtree: true, attributes: true, attributeFilter: ['loading']} );
throttledTransform();
```

**Comment by mathiasbynens** [comment]
I get that turning `src`/`srcset` into `data-src` dynamically is not feasible.

But @aFarkas, how would you feel about dropping this library's dependency on `class="lazyload"` in favor of the soon-to-be-standard `loading=lazy`? Of course, this would be a breaking change, so it would require a new semver-major release. But it would simplify the markup that developers would need:

```html
<!-- before -->
<img alt="..." data-src="cats.jpg" loading="lazy" class="lazyload">
```

...to:

```html
<!-- after -->
<img alt="..." data-src="cats.jpg" loading="lazy">
```

We don't need `class="lazyload"` since `loading="lazy"` already signals that the image is supposed to be lazy-loaded.

**Comment by momendo** [comment]
Is it possible to configure which images or iframes will be modified to native loading in the plugin?

I don't agree with Google Chrome's lazy loading heuristic for IFRAMEs.

**Comment by bkarlson** [comment]
guys, what's your experience with native lazyloading? It seems to be far inferior to lazysizes due to lack of config. 

For example, if there're 100 thumbs on a page with only 12-20 visible, Chrome will fire load for 80%+ of them, despite the fact that most of them are way below the fold. They have some connection-based heuristics to detect how much content to queue, but in our tests it proven to be way too aggressive and even on slower connections Chrome will preload way too many off-viewport images for no good reason.

**Comment by scott-thrillist** [comment]
@bkarlson 
> Chrome will preload way too many off-viewport images for no good reason.

I'm seeing this same behavior myself. I'm guessing because Chrome has chosen to be more conservative in pre-loading below the fold images in case the user scrolls fast and/or the connection is slow.

I wish it was at least smart about it and would load a large number of images in succession, like only load the first 5 simultaneously. Then when one is finished start loading number 6 and so forth.

**Comment by scott-thrillist** [comment]
If anyone is reading, we've reverted to using lazysizes over the native loading attribute and the user experience is better. Our pagespeed insights score is roughly the same.

Also of note- don't use the loading="lazy" attribute on above the fold images as it will cause a flash. Best practice above the fold is no lazyload and also prefetch the image using the `<link preload />` tag. Night and day difference for UX
