### ISSUE TITLE
Multiple uses of lib on a page

### ISSUE THREAD

**Issue by jpuri** [aFarkas/lazysizes#643]
Hi @aFarkas ,

Thanks a lot for the awesome lib.

I am working on a page builder and I added this lib for lazy loading of images, it works great 👍 . The issue I am facing is that sometimes user templates already are using a version of the lib, they import their templates and use page builder to add more content on it.

This can result in library included twice on the page, in those cases the shared global `lazySizesConfig` gives trouble. Do you have any suggestions for this ? Thanks in advance.

**Comment by aFarkas** [comment]
While lazySizes supports multiple modules on one page I don't recommend doing it. The normal way is to use `import`/`require` and do not use the `lazySizesConfig` at all.


```js
import lazySizes from 'lazysizes';
// other imports ...

//
lazySizes.cfg.lazyClass = 'lazy';
```

In this case it is also wise to always change the `lazyClass` with your own namespaced version otherwise your lazysizes instance might conflict with the markup of the other page.

Due to the fact that you don't have control over the other page you might be able to workaround by simply defining [all options](https://github.com/aFarkas/lazysizes/blob/gh-pages/src/lazysizes-core.js#L242-L263).

Your code might look like this:

```js
// helper/store-global-ls-options.js
export window. lazySizesConfig || null;
```

```js
import originalLazySizesConfig from './helper/store-global-ls-options';
import lazySizes from 'lazysizes';

Object.assign(lazySizes.cfg, {
	lazyClass: 'namespaced-lazyload',
	loadedClass: 'lazyloaded',
	loadingClass: 'lazyloading',
	preloadClass: 'lazypreload',
	errorClass: 'lazyerror',
	//strictClass: 'lazystrict',
	autosizesClass: 'lazyautosizes',
	srcAttr: 'data-src',
	srcsetAttr: 'data-srcset',
	sizesAttr: 'data-sizes',
	//preloadAfterLoad: false,
	minSize: 40,
	customMedia: {},
	init: true,
	expFactor: 1.5,
	hFac: 0.8,
	loadMode: 2,
	loadHidden: true,
	ricTimeout: 0,
	throttleDelay: 125,
});

if (originalLazySizesConfig) {
    window. lazySizesConfig = originalLazySizesConfig;
} else if('lazySizesConfig' in window) {
    delete window. lazySizesConfig;
}
```
