### ISSUE TITLE
WebP backgrounds

### ISSUE THREAD

**Issue by RawMajkel** [aFarkas/lazysizes#656]
Is there any possibility to create double "data-bg" attribute?
In my projects I first use the default version of my background-image and then the webp one, so the browsers that don't support webp aren't confused.

In css it looks like this:
`background-image:url('background1.jpg');
background-image:url('background1.webp');`

**Comment by aFarkas** [comment]
I very dislike using in markup background images. Question: Why do you use it at all. In case you want to use `object-fit`. There is a good full polyfill or a partial polyfill by lazySizes.

In any case you can simply do the following:

```html
<style>
.special-bg.lazyloaded,
.special-bg.lazyloading {
    background-image:url('background1.jpg'); background-image:url('background1.webp');
}
</style>

<div class="special-bg lazyload">
</div>
```

Additionally you can simply create your own plugin. It's easy.

**Comment by RawMajkel** [comment]
Well, for optimization purposes of course. Webp can greatly reduce size of the file. Some browsers, like Safari and IE don't support this tho. But modern ones, like Chrome or Firefox are used to see two background-images and then choose if they can handle a better webp version.

I'd just like it to be lazyloaded as well.
Eventually, I'll try to do this by my own.

**Comment by aFarkas** [comment]
> Well, for optimization purposes of course. Webp can greatly reduce size of the file.

Yes of course for this you can use the `picture` element.

**Comment by aFarkas** [comment]
Again in most cases I very dislike using background images. If you are stuck with it you can use the following plugin: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/bgset

**Comment by bahra87** [comment]
I actually like to use backgrounds, especially with Bootstrap in the context of pure html sliders. 

@aFarkas, I love and use your lazysizes for years, with absolute satisfaction in many client projects. 

For anyone interested, I have solved the "problem" for my needs quite simply. Tests so far have shown no dropouts or the like. Google Pagespeed is also satisfied.

First I check with a tiny script (6ms load time) if the browser can deliver webp or not and set the appropriate class in the html tag. Then I manipulate aFarka's plugin for the data-bg attribute so that the class is queried in the html tag and if not webp capable the file extension is set by *.jpg.

For me this solution has the charm that I don't have to set another data-attribute, but only provide the file with the same name with *.webp and *.jpg on the server. I consider a fallback for the fallback unnecessary.

Feel free to adapt the code to your needs or even include it in the repositry.

```
// Check Browsercompatibility for webp by onload or onerror

var root = document.getElementsByTagName( 'html' )[0]; 
function hasWebP() {
    var rv = $.Deferred(), img = new Image();
    img.onload = function() { rv.resolve(); };
    img.onerror = function() { rv.reject(); };
    img.src = 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACyAgCdASoCAAIALmk0mk0iIiIiIgBoSygABc6WWgAA/veff/0PP8bA//LwYAAA';
    return rv.promise();
}

// Set Class for webp-detection to html
hasWebP().then(function() {
    root.className += 'webp'
}, function() {
    root.className += 'no-webp'
});

// Edited layzbeforeunveil data-bg support to check webp support and switch between image extension to fallback no webp support

document.addEventListener('lazybeforeunveil', function(e){
    var bg = e.target.getAttribute('data-bg');

    if(bg && root.classList.contains('webp')){
        e.target.style.backgroundImage = 'url(' + bg + ')';
    }
    else if(bg && root.classList.contains('no-webp')){
        var fallbackbg = bg.replace(/\b(webp)\b/g, "jpg");
        e.target.style.backgroundImage = 'url(' + fallbackbg + ')';
    }
    else if(bg) {
        e.target.style.backgroundImage = 'url(' + bg + ')';
    }
});
```
