### ISSUE TITLE
lazyload background image for an inline element, is possible?

### ISSUE THREAD

**Issue by mxkeke** [aFarkas/lazysizes#668]
Hello,
how can I use lazyload behavior with a background image for an inline element?
`<div style="background-image: url("myimage.png 1x, myimage@2x.png 2x");" class="lazyload">...</div>`

Thanks.

**Comment by localnetwork** [comment]
Include the additional js(ls.bgset) in plugins/bgset folder

<div class="lazyload" data-bgset="your-image-src">
</div>

**Comment by localnetwork** [comment]
`<div class="lazyload" data-bgset="your-image-src"></div>"`

**Comment by mxkeke** [comment]
Ok, thanks.

**Comment by ciekawy** [comment]
and what if its not possible to alter the style attr (as it is generated by third party plugin)?

**Comment by localnetwork** [comment]
nope, no need to add style attribute since the ls.bgset plugin will automatically adds style attribute to your element.

<div class="lazyload" data-bgset="your-image-src">

</div>


It will look like this once you reached that div.

<div class="lazyloaded" data-bgset="your-image-src" style="background-image: url('your-image-src');">

</div>
