### ISSUE TITLE
Decreasing minSize below 40 stops DOM traversal but also stops sizes calculation

### ISSUE THREAD

**Issue by Hlsgs** [aFarkas/lazysizes#671]
Decreasing `minSize` below 40 appears to indeed stop the DOM traversal if `new minSize < parent-width  <= 40`, but the sizes calculation always returns the width of said parent, disregarding explicit `data-aspectratio` and implicit ratio calculated from the width and height attributes.

I'm using lazysizes 5.1.0 with object-fit, parent-fit and respimg.

**Comment by aFarkas** [comment]
I assume you have wrong expectations the `data-aspecratio` and `width` and `height` attributes are about the physical image dimension while the `minSizes` option is about the layout dimension of the `img`.

If you still think this is an issue please follow our bugreport template:
https://github.com/aFarkas/lazysizes/blob/gh-pages/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Hlsgs** [comment]
I'm aware of the purpose of those settings.

I can't figure out how to properly set `minSize` in jsfiddle because of the iframe used, however, I have produced an example in which the mentioned behaviour manifests even with sizes over the default 40px:

https://jsfiddle.net/Hlsgs/0otjmkbs/17/

What's going on here?

**Comment by aFarkas** [comment]
I had a hard coded minSize for height also. I decided to remove it entirely instead of hooking into the config because in case of `object-fit` I assume authors will produce a proper `height`. (The `minSize` is simply a workaround for the fact that we cannot detect wether the author of the page has set `width`/`height` explicitly to a value. Additionally I assumed no one would use `srcset` on so small images).

Could you please test wether this fixes your issue? Thank you very much!

**Comment by Hlsgs** [comment]
Yes, all good with the fix. Thank you for your excellent work and support!
