### ISSUE TITLE
Visibility & overflow

### ISSUE THREAD

**Issue by Ninos** [aFarkas/lazysizes#687]
**Describe the bug**
lazysizes should check for visibility != hidden & not outside overflow hidden

**To Reproduce**
```
<div container>
    <img lazyloaded>
    <img lazyloaded>
</div>
```

**What is the expected behavior**
Lazyload only if image is not visibility hidden & inside of div container, if container has overflow hidden.

**What happened instead**
Images are always lazyloaded

**In what environment (browser/device etc.) does this bug happen/not happen:**
All

**Comment by aFarkas** [comment]
I check for these things. You can see the [visibility](https://github.com/aFarkas/lazysizes/blob/gh-pages/src/lazysizes-core.js#L394) and the [overflow nesting](https://github.com/aFarkas/lazysizes/blob/gh-pages/src/lazysizes-core.js#L395). However the overflow nesting is only checked on positioned elements (i.e.: elements that don't have `position: static`).

If lazysizes sees those images they are loaded with a lower priority compared to really visible images. But they are should be loaded because they might come into view soon and the user shouldn't be watching how the images he/she wants to see loading.

For the visibility check you can simply set the `loadHidden` option to `false` and for the nested overflow visibility you could add the `data-expand="10"` attribute. But really I wouldn't do this under normal situations. It doesn't give you a better performance and decreases the user experience.
