### ISSUE TITLE
Unveilhooks.js Trouble With LazyLoading Background Images

### ISSUE THREAD

**Issue by AdventurouslySocial** [aFarkas/lazysizes#700]
I've tried two methods. Both demonstrated below.

First I tried:

**CSS**
   `   .bg-stage.lazyloaded {
     background-image: url("/wp-content/uploads/2019/09/redlights_bg.jpg");
     background-size: cover;
     }`

**Page Builder Code**
    
    <section class="elementor-element elementor-element-71cfd82 elementor-section-full_width 
    elementor-section-height-min-height bg-stage lazyload elementor-section-height-default
     elementor-section-items-middle elementor-section elementor-top-section" 
    data-id="71cfd82" data-element_type="section" 
    data-settings="{&quot;background_background&quot;:&quot;classic&quot;}">
    </section>

It displays the background image, but it does _not_ lazyload the background image.

Secondly, I tried:

`<section class="elementor-element elementor-element-d87a325 elementor-section-full_width elementor-section-height-min-height lazyload elementor-section-height-default elementor-section-items-middle elementor-section elementor-top-section" data-id="d87a325" data-element_type="section" data-bg="/wp-content/uploads/2019/09/redlights_bg.jpg">`

This too displays the background image, but does not apply lazyloading.

I am using the Wordpress plugin for Lazysizes found here: https://wordpress.org/plugins/lazysizes/

I have checked to ensure both _**lazysizes.min.js - v5.0.0**_ and _**lazysizes.unveilhooks.min.js - v5.0.0**_ are both enqueued without console errors.

I am unsure of what I should do and would greatly appreciate insight and assistance. Thank you.

**Comment by AdventurouslySocial** [comment]
I have found some **_measure of success_** using _ls.bgset.min.js to lazyload background images by applying the css of 'lazyload' and the attribute of data-bg="image.jpg"

However I am seeing each lazyloaded background image loaded twice. 
First by lazysizes.unveilhooks.min.js and a second time by 'other'. 

I don't know what is causing this behavior and am in need of guidance, thank you.

**Comment by aFarkas** [comment]
About all your problems in general as long as you do not provide a testcase demonstrating the issues. I can't tell you the issue.

In general lazysizes applies the `lazyloaded` only after the element is in view as also transforms `data-bg` only in those cases.

About your second issue. This is in general either caused by specific developer options only applied as long as your network panel is open or by wrong http headers set on your server. Search for thinks like `no-cache` headers and similar.

Please close if this helps or provide a test case.
