### ISSUE TITLE
I dont know how to inject 'lazysizes' in Angular 8

### ISSUE THREAD

**Issue by azurehari** [aFarkas/lazysizes#706]
Hi sir,
I dont know how to inject lazysizes library in Angular 8. Kindly I request you to help me please.

I have added lazysizes via NPM

`npm install lazysizes --save`
and i have added below in angular.json file

`"node_modules/lazysizes/lazysizes.min.js",`

and i have added below in "my-component.module.ts"
import 'lazysizes'

and in my html i have added,
`<img class="lazyload" data-src="<img-url>">`

Its is not working so far, all images loaded when page loads but not loading as lazyload.. please help me get rid out of this issue.. what should i do to make this library works in angular 8?

**Comment by aFarkas** [comment]
To me it seems that you have injected lazysizes otherwise there your `data-src="" class="lazyload"` wouldn't be transformed to `src="" class="lazyloaded"`.

For the fact that all images are loaded immediately I can only guess because you do not provide any reproducible information. The most often reason for this is that all images are in the viewport at the time lazysizes runs. You should be able to fix this by defining a proper height.

Beside this:

`import 'lazysizes';`  will load `node_modules/lazysizes/lazysizes.js` not the `*.min.js` file.
Please follow the issue template if you want help.

**Comment by luckyboykg** [comment]
From angular 2.x and more, I can make it work by this way:
Use this script import in your index.html file

```
<script
            async
            src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.2.2/lazysizes.min.js"
            crossorigin="anonymous"
        ></script>
```

And use Img tag in your component:

```
<img
                            [ngClass]="['lazyload']"
                            [src]="defaultImage"
                            [attr.data-src]="previewStoryImage"
                        />
```

-[ngClass]: because your class we be changed by angular
-[attr.data-src]: the custom attribute in angular
