### ISSUE TITLE
Lazyloading fails silently in Firefox

### ISSUE THREAD

**Issue by lunelson** [aFarkas/lazysizes#747]
**Describe the bug**
Images have stopped lazy-loading on Firefox.

**To Reproduce**
Load the following URL in a current version of FF.
https://www.maxkaminski.de/

**What is the expected behavior**
Images should load

**What happened instead**
Nothing seems to happen.

**In what environment (browser/device etc.) does this bug happen/not happen:**
Works in Chrome and Safari. Previously, it worked in all browsers

**Comment by philippdaun** [comment]
I can confirm this behaviour on Firefox 73.0 using lazysizes 5.2.0. Working as expected on latest Chrome & Safari (all MacOS 10.15.3)

lazysizes seems to be missing the images completely. No network requests. No errors in the console. The `lazyloading` class is never added.

Since it's working in other browsers, I suspect it's more of a DOM issue maybe than any changed logic in v5.

**Comment by philippdaun** [comment]
Found the problem, it's unrelated to lazysizes. This issue can be closed.

It's a bug with the Nuxt framework which is bungling the `srcset` placeholder data URIs. 

Suggested fix for @lunelson: Instead of setting the srcset placeholder as an attribute, pass in a variable. Nuxt won't touch it then.

Before:

```html
<img srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
````

After:

```html
<img :srcset="empty">
````
```js
export default {
  data () {
    return {
      empty: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
    }
  }
}
```

**Comment by lunelson** [comment]
@philippdaun Thank you!! What a great catch. So Nuxt was just inserting an extra space in the data URL? ...and somehow invalidating the `img` markup entirely, so that lazysizes was then not triggered?

**Comment by philippdaun** [comment]
@lunelson Almost. Nuxt added a space after `base64,` which is apparently a valid URL in Chrome and Safari but is interpreted as a broken image by Firefox. Hence the image wasn't flagged as `.complete` and lazyload wouldn't pick it up.

Hard to say if it's Nuxt itself or some transient dependency but at least there's a simple fix 🍇
