### ISSUE TITLE
Resolution switching no longer works?

### ISSUE THREAD

**Issue by f1hornet** [aFarkas/lazysizes#768]
**Describe the bug**
Hi Alexander. I am using your jsFiddle as the basis for this bug report: http://jsfiddle.net/trixta/bfqqnosp/embedded/result/

Basically when I run that fiddle the middle graphic never changes. I have tested it on my iPhone and iPad in both landscape and portrait mode and the image never adjusts to the new resolution

**To Reproduce**
[jsfiddle.net](http://jsfiddle.net/trixta/bfqqnosp/embedded/result/) - view issue on iPhone and iPad

**Steps to reproduce the behavior:**
Nothing complicated - image never changes. It can also be replicated on a browser.

**What is the expected behavior**
I would expect to see a different image between iPhone portrait and iPad landscape. 

**What happened instead**
see above

**In what environment (browser/device etc.) does this bug happen/not happen:**
see above

**Comment by strarsis** [comment]
In my case, the image doesn't appear at all in Safari on iOS (browserstack.com).

**Comment by aFarkas** [comment]
@f1hornet:

it works as designed. maybe read a little bit about the standard. your bad expectations have nothing to do with lazysizes, but the fact that you don't know how the standard works.

**Comment by f1hornet** [comment]
Perhaps you could enlighten me? Or point me in the direction of the documentation you mention? Just looking for a bit of help not criticizing you or your baby!

**Comment by aFarkas** [comment]
@f1hornet: Really? https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element

**Comment by LeoSeyers** [comment]
@aFarkas I've seen a lot of angry posts lately, just to tell you everything works so fine with lazysizes accross all the projets i'm working on and I'm so happy with its features
so again, on the behalf of all happy developers like me, thank you Alexander and all the contributors involved :)

**Comment by f1hornet** [comment]
Mate if you are having a bad day don't take it out on the general public. Go for a walk, relax, do something you like....

**Comment by f1hornet** [comment]
and do explain what your middle image in the fiddle is supposed to do because it looks broken!

**Comment by aFarkas** [comment]
repost from f1hornet:
> and do explain what your middle image in the fiddle is supposed to do because it looks broken!

This is my point: This example is explained by using the term "resolution switching".  "Resolution switching" is not my idea it has nothing to do with lazysizes but it is standardized by the whatwg. If you are a FE developer who knows the standard you will understand if not  you have to learn it, but please don't expect me to be your teacher. 

I have done it for so many time and I can't and won't anymore.

**Comment by aFarkas** [comment]
I really need to recapitulate on this because I do a nicotine detox, was indeed quite angry and couldn't answer appropriately. But this issue is crazy.

So we have this [demo](http://jsfiddle.net/trixta/bfqqnosp/embedded/result/) and it uses two technical terms (**art direction** and **resolution switching**) to describe the two varying features on the demo page. 

And now you have the following situation:

a) you don't understand what those terms mean
b) you would expect that both varying features should work the same way and therefore suspect a bug with one of them

How do you solve this problem:

a) Search for those technical terms to check wether they make any difference in your assumption/opinion
or 
b) or stay uninformed and directly write a bug report, because the fact that you don't understand 100% of the written descriptive text on those demo pages can't change the fact that your personal expectation has to be satisfied
