### ISSUE TITLE
Help the HTML standard with the approach for when to load lazy images

### ISSUE THREAD

**Issue by zcorpan** [aFarkas/lazysizes#769]
> Intelligent prefetch/Intelligent resource prioritization: lazysizes prefetches/preloads near the view assets to improve user experience, but only while the browser network is idling (see also expand, expFactor and loadMode options). This way in view elements are loaded faster and near of view images are preloaded lazily before they come into view.

https://github.com/aFarkas/lazysizes#what-makes-lazysizes-so-awesome

Lazy-loading images was [recently added](https://github.com/whatwg/html/pull/3752) as a native feature to HTML, and browsers are currently trying to figure out *when* lazy images should start loading.

Would the maintainers of this project be willing to chime in here: https://github.com/whatwg/html/issues/5408 and explain the approach taken here in more detail, and the rationale? I think this can help inform what browsers should do for `loading=lazy` images.

Thanks! ❤️

**Comment by strarsis** [comment]
@zcorpan: But there is native standard yet to contain/cover the image into parent element on client-side? This is the main use-case for lazysizes in my projects.

**Comment by zcorpan** [comment]
Like the CSS object-fit property?

**Comment by strarsis** [comment]
@zcorpan: Yes! With dynamic content the element height cannot be known in advance (well with some complicated server-side browser rendering maybe, but this will still not take the text breaking hyphens, etc into account). Therefore `sizes` cannot be used for `cover` fit because this requires the height.

**Comment by zcorpan** [comment]
Is it something the "auto sizes" feature in lazysizes enables? I don't really follow, a demo might help.

**Comment by strarsis** [comment]
@zcorpan: Sure: https://codepen.io/strarsis/pen/gOaMgRN

**Comment by aFarkas** [comment]
@zcorpan 
Yes we already talked about this in the standard `autosize` feature. This is why we need the h descriptor. (The demo of @strarsis uses a `data-aspectratio` attribute instead of the standard decscriptor.). 

@strarsis 
The `data-aspectratio` has to be defined on the `source` element not the `img`.

**Comment by zcorpan** [comment]
OK, then I think the following issues cover the needs of @strarsis demo:

https://github.com/whatwg/html/issues/4654
https://github.com/whatwg/html/issues/4968

The `h` descriptor could provide intrinsic aspect ratio too (instead of `width`/`height` on `source`)

https://github.com/whatwg/html/issues/2973

**Comment by aFarkas** [comment]
@zcorpan 
Do you also plan to implement some kind of `optimumx` or `maxdpr` attribute to constrain the resolution of an image?

**Comment by zcorpan** [comment]
@aFarkas no such plan currently AFAIK. Browsers can choose to cap their "x" to avoid downloading unnecessarily large images though when choosing from `srcset`.
