### ISSUE TITLE
Remove delay when image is inside tabs

### ISSUE THREAD

**Issue by chille1987** [aFarkas/lazysizes#777]
https://jsfiddle.net/chille1987/nbw2fesm/7/

Is it possible to remove delay when the images are inside tabs? I would like to when I click on a tab to automatically load image. In the example above you'll see that there is a slight delay when you click ona a tab first time, once the images are loaded everything works fine.

**Comment by aFarkas** [comment]
This is not possible because you hide those elements with `display: none`. Therefore it is not possible to detect wether those images are close to the viewport.

If you would hide the panels using `visibility: hidden` it would be possible.

Note: You can still force to download earlier by using the JS API (Simply read the manual).
