### ISSUE TITLE
Acting weirdly in the latest firefox v36.0.1

### ISSUE THREAD

**Issue by isaumya** [aFarkas/lazysizes#79]
Hey guys,
First of all thanks a lot for this awesome script. I've been testing your plugin thoroughly and the lazy load works perfectly on chrome and opera, but in firefox it work very weirdly. I've using this lazysize on the wordpress site using the WP Retix Pro plugin (https://wordpress.org/plugins/wp-retina-2x/) which is incorporated with lazysize. A lot of image doesn't load. Even if it is  at the top of the page.

I've contacted the plugin author @tigroumeow but he said that there is no problem with the plugin end. So I would be glad if someone from the lazysize team take a look at this issue.

As my site is a live site and many people visit it every second, I cant keep the issue on the live site to show you guys. So I have deactivated lazysize for now until the issue got fixed. Instead I've screencasts a video where you will see the issue in details
https://www.youtube.com/watch?v=43DnBAEk3po&hd=1

I'll be really greatful if someone can help me with this.

**Comment by aFarkas** [comment]
Could you please give me the url of your page? This would help dramatically.

**Comment by isaumya** [comment]
ofcourse here is my site : https://www.isaumya.com
but please note that as this is a live site with a decent amount of viewers, I've disabled the lazysize temporarily for the issue I've shown in the video :)

**Comment by aFarkas** [comment]
Well, this is hard. Basically at this point lazySizes already did everything, the only possible things are a) it did not find/invoke picturefill, b) you have changed your ``srcset` or ``picture`` config in FF from disabled to enabled or you use FF38 or c) there is an error in picturefill.

Your current https://www.isaumya.com/blog/ has one retina image. (Blogpost: Atlast! The new design has been released with Genesis). Do you see this image in FF?)

**Comment by isaumya** [comment]
Yes currently everything is loading fine in firefox as the lazysize has been disabled. but as soon as I enabled it all things starts messing up. For a live test, if you want I can enable lazysize again on my site for few minutes and then you can test it thoroughly. Specially the shop section, blog section and other places. I hope it will help you to see the issue by yourself. Let me know if I enable it now and if you wanna see the issue live? Will be waiting for your reply.

**Comment by aFarkas** [comment]
This would be great! Enable it, just watching here.

**Comment by isaumya** [comment]
It has been enabled and will remain enable unless you done testing it thoroughly. Do test my site on all major browsers, you will see the firefox specific issue. I didn't find this kind of issues in chrome or opera. But as I'm in windows didnt have the luck to test it in safari.
Let me know when you are done testing it, so that I can disable it. Will be waiting for your reply conformation.

**Comment by aFarkas** [comment]
ok, you can turn it off again. sorry, for taking so long.

**Comment by isaumya** [comment]
Thats alright my friend. :) But what matters is did you find the issue behind this? I've turned it off for now :)

**Comment by aFarkas** [comment]
Ok, why did this take sooo long. The debugger in new FF's devtools is a piece of shit. I only needed to set a breakpoint and guess what the debugger doesn't simply work. I hate it.

So yeah, the reason is quite simple. As soon as lazySizes is included picturefill is not included. But lazySizes either need picturefill or respimage to do the polyfill work. So you can fix it by just adding one of those scripts your own.

But we should hand it over to @tigroumeow again. So that he can make sure that both scripts are included.

**Comment by isaumya** [comment]
But Retina 2x plugin already uses picturefill and its already working on my site. Did you see that?

**Comment by aFarkas** [comment]
Yes I know. But it seems, that as soon as you request lazySizes picturefill isn't added anymore

**Comment by isaumya** [comment]
Well can you tell how to solve this weird issue? so that @tigroumeow can fix it. Also if this is the the issue what you are saying, then how it is not throwing any issue over chrome or opera? It will be really helpful if you give a solution for this weird issue. Like how this issue can be solved.

**Comment by aFarkas** [comment]
Because chrome, opera and safari do support this natively. I think @tigroumeow  thought, that lazysizes is a solution, that also polyfills. But in fact lazySizes relays on polyfills. But also can be used without a polyfill, but in that case an additionaly ``data-src`` has to be added.

I'm pretty sure he will understand as soon as he reads [this](#issuecomment-80703999).

**Comment by aFarkas** [comment]
And for you, you can fix it before he has done it by just adding picturefill manually.

**Comment by isaumya** [comment]
I've already emailed @tigroumeow with the link of this thread. As he is from japan, its almost 5:40am there and he might be sleeping. I'm pretty sure that he will reply on this thread as soon as he sees it. Lets see what he have to say about this before doing any manual edit on his plugin code :) Every developer should respect others work, thats what I believe in. So let's see what he has to say about this. I'm pretty sure that if he understand the issue he will fix it :)

**Comment by tigroumeow** [comment]
Ohayogozaimasu guys! Indeed, I thought lazySizes was standalone. I will fix this on Monday :) Thanks for all the debugging.

Not sure if I should start another thread about it but how is the script "SEO Improved"? Is it SEO for the website as a whole or SEO for the images? Personally, if I use a lazy script on my website, then Google will stop referencing the images. Did you actually find a solution for that? "src-set" is ignored by Google until now.

**Comment by aFarkas** [comment]
about this seo thing. It means, that lazyloaded assets (images) aren't hidden from googlebot. The solution is actually pretty simple. Since at least a half year the goolgebot executes JS, the only thing, that googlebot doesn't do is scrolling. The solution are two lines: [here](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L126) and [here](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L197). This was added with version 1.0.1, but if you update your version you can test it on your site with google webmaster tools and the fetch as google tool.

**Comment by tigroumeow** [comment]
Super, that sounds awesome. Just a last thing before I release a new version of the plugin. You wrote 

> Lazysizes does not need any JS configuration: Add the class "lazyload" to your images/iframes in conjunction with a data-src or data-srcset attribute."

I am using **data-srcset** if lazysizes is used, otherwise, with PictureFill alone, I use **srcset**. Can't I use srcset with both? Google should be able to reference both data-srcset and srcset?

**Comment by aFarkas** [comment]
Sadly, no. lazySizes needs ``data-srcset`` or another custom attribute otherwise, the browser already would load something.

With no configuration I mean you won't need to create instances or write configure something in JS.

**Comment by tigroumeow** [comment]
Okay, understood. Thanks for all your help, that was very helpful :)
