### ISSUE TITLE
Image load extremely slow when using lazyload

### ISSUE THREAD

**Issue by JetLewis** [aFarkas/lazysizes#797]
Some, but not all, of my images that use lazyload are loading extremely slowly when coming into view,

see example: https://atelierdesign.be/about-us/ (references section)

This is what happens when lazyload is used:

![Annotation 2020-06-08 122402](https://user-images.githubusercontent.com/4490827/84021753-7b252d80-a985-11ea-8fa9-67bd5a6ac0f5.png)

`<img class="lazyload" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 2 1'%3E%3C/svg%3E" data-srcset="<?php echo  $image_srcset; ?>" data-sizes="auto" alt="<?php alt($image); ?>">`

(Removing the src attr didn't change anything so it's not coming from there)

This is when I don't:

![Annotation 2020-06-08 123441](https://user-images.githubusercontent.com/4490827/84021763-7eb8b480-a985-11ea-83b2-0aa72e583160.png)

`<img class=""  srcset="<?php echo  $image_srcset; ?>" alt="<?php alt($image); ?>">`

The website is made with wordpress, I used w3 total cache and image are webm converted.

**Comment by aFarkas** [comment]
I just had a look at your page and I'm 99.9% certain that this has nothing to do with lazysizes. In general problems in the network tab can't really provoked by lazySizes because lazySizes might initiate a download but doesn't have any further control over it.

In your case it extremely certain that your problem is caused by your video file which loads multiple times and seems to block other content downloads. So by using lazySizes you delay the image download until the video download starts and therefore images can't download at a good speed.

To test my assumption please remove your video component and check wether your images are loading faster then.

**Comment by JetLewis** [comment]
Good call! The video was changed to a very large file without me being noticed, sorry for bothering you and thanks very much for your reply.
