### ISSUE TITLE
Fix forced layout shift

### ISSUE THREAD

**Issue by charisTheo** [aFarkas/lazysizes#802]
`clientHeight` and `clientWidth` in the lines below are causing a forced layout reflow which harms performance. 

https://github.com/aFarkas/lazysizes/blob/a2f37ec2371bff523ea8b94800682e4ec3596b9b/lazysizes.js#L369-L371

![image](https://user-images.githubusercontent.com/9759549/84662004-1765ac00-af13-11ea-8439-d58622c41294.png)

![image](https://user-images.githubusercontent.com/9759549/84662174-585dc080-af13-11ea-9ab6-3be82144e10d.png)

## Proposed fix:
Get element's dimensions once and reference them later without requesting dimensions repeatedly in the same block.

```js
var docElemRec = docElem.getBoundingClientRect();
defaultExpand = (!lazySizesCfg.expand || lazySizesCfg.expand < 1) ? 
 	docElemRec.height > 500 && docElemRec.width > 500 ? 500 : 370 : 
 	lazySizesCfg.expand; 
```

**Comment by aFarkas** [comment]
Please provide a testcase that demonstrates your issue. Your proposed fix wouldn't work.

**Comment by charisTheo** [comment]
Try to uncomment [this code](https://glitch.com/edit/#!/emphasized-savory-ring?path=lazysizes.js%3A372%3A12) in this Glitch.

I compared using the Performance tab in Chrome Dev Tools:
- Fast 3G Network
- 4x CPU slowdown
- Remove head and body element
- Hit the "Start profiling and reload page" button

Here are the results from multiple runs before and after uncommenting the code: 

## First run

### Before

![before](https://user-images.githubusercontent.com/9759549/104105615-48d70800-52a7-11eb-9bdb-16a67f555dd4.png)

### After

![after](https://user-images.githubusercontent.com/9759549/104105647-7b810080-52a7-11eb-9e77-596dcbb467df.png)

## Second run

### Before

![before-2](https://user-images.githubusercontent.com/9759549/104105660-905d9400-52a7-11eb-81f2-f5281d10b204.png)

### After

![after-2](https://user-images.githubusercontent.com/9759549/104105667-9784a200-52a7-11eb-83d9-0fbab738bb01.png)

## Third run

### Before

![before-2-1](https://user-images.githubusercontent.com/9759549/104105656-8a67b300-52a7-11eb-98ce-28a6276b6083.png)

### After

![after-2-1](https://user-images.githubusercontent.com/9759549/104105685-be42d880-52a7-11eb-82ed-839a9ab0471b.png)

## Results

**Scripting**, **Rendering** and **Painting** times all improved after uncommenting the code.

**Comment by aFarkas** [comment]
@charisTheo 
Sorry, but I can not follow. You first opened an issue about layout thrashing and now you created a demo page that doesn't involve layout thrashing.

Do you want to say that using `getBoundingClientRect` is so much faster than using `clientWidth`/`clientHeight` at the same position? 

Your test setup in general is quite questionable. Your performance tab records 1000 of things in the initialization phase. Yet instead of a detailed view of only the optimized part, I get a summary of those thousand recorded things?

In my test - if I slow down to get similar total numbers as you - the hole time spend in `checkElements` (the part of code that you changed minimally) is around 12ms (mostly because I also count in outside calls to unveilElement...). It sounds quite magic to improve script performance by 100ms by a sole improvement of a part that only takes 12ms. 

<img width="882" alt="Bildschirmfoto 2021-01-09 um 20 03 22" src="https://user-images.githubusercontent.com/188254/104107285-4d0d2080-52bb-11eb-921f-e454af0a0ce3.png">
