### ISSUE TITLE
lazyloaded class set, but no background-image set on hard refresh

### ISSUE THREAD

**Issue by Ceyar** [aFarkas/lazysizes#815]
Hello,

I'm trying to use lazysizes and bgset plugin with my background images. 

All seem's to work fine but sometimes when I hard refresh the page (command + shift + R on mac) the images are not loaded.
But the things is that the class `lazyloaded` is added to the element. It's a little bit random, sometimes it set the background image url and sometimes it doesn't.

When we make a basic reload, that work.

You can see the [issue here](https://layout.stage.campfire.ch/issue/agenda-detail.html).
I use Glide JS for this example but the issue appears on basic background element without plugin behind.

Tested on (macbook pro):
- Chrome: work on reload but on hard refresh, random work
- Firefox: Working
- Safari: Do not work at all -_-'
- Edge on mac: same as Chrome

Do you have any Idea?

By the way, thank you for your plugins, and thank you for your help.

**Comment by studiojeden** [comment]
I have slider based on background images:
https://www.seaandlake.pl/

Not sure does it work with background images.

**Comment by aFarkas** [comment]
@Ceyar
This normally happens if the slider copies (via clone or innerHTML for example) and re-injects HTML. This technique will break any references.

You can fix this by starting lazysizes after invoking your slider. Search for "init" in the readme. Another way would be to fix the slider because this behavior is problematic in multiple ways.
