### ISSUE TITLE
[Violation] chrome

### ISSUE THREAD

**Issue by merijnponzo** [aFarkas/lazysizes#832]
Hello, i've got 
```
[Violation] 'setTimeout' handler took 54ms lazysizes.js:165 
[Violation] 'requestAnimationFrame' handler took 57ms
```
In the latest google chrome Version 86.0.4240.80 (Official Build) (x86_64)
Lazysizes "lazysizes": "^5.2.2",

I use lazysizes within nuxt by configuring it as a plugin:
```
import Vue from 'vue'
import Lazysizes from 'lazysizes'
import '@/node_modules/lazysizes/plugins/respimg/ls.respimg'
import '@/node_modules/lazysizes/plugins/object-fit/ls.object-fit'
import '@/node_modules/lazysizes/plugins/parent-fit/ls.parent-fit'
Vue.use(Lazysizes)
```

within my page template
```
<picture class="picture"  >
              <template v-if="visual.sizes.thumbnail">
                <source
                class="img lazyload"
                :data-srcset="visual.sizes.thumbnail"
                media="(max-width: 640px)" />
              </template>
              <template v-if="visual.sizes.medium">
                <source
                class="img lazyload"
                :data-srcset="visual.sizes.medium"
                media="(max-width: 1200px)" />
              </template>
              <img
                :data-src="visual.sizes.large"
                class="img  lazyload"
                data-sizes="auto"/>
            </picture>
```

Should i ignore this message?

**Comment by aFarkas** [comment]
> Should i ignore this message?

I obviously can not tell this because of the code you are giving here. In general in a large project this can happen and it normally only happens during initialization. In case this happens during scroll it should be considered a major issue. During initialization it totally depends.

From my current standpoint I can not even decide wether there is something wrong with lazysizes or it is because you are transforming 15+ images at once (and you must transform so many images at once). 

If you would provide a full url I could have a look, but I can not promise anything.

Please reopen if you provide the url to the full example.

**Comment by ryanhallinger** [comment]
Hi Alexandar,

I have just started encountering a similar issue. Google Chrome `Version 87.0.4280.66 (Official Build) (64-bit)` returns the message `[Violation] 'setTimeout' handler took 73ms lazysizes.min.js?ver=5.2.2:3`

The message is displayed when Google Chrome is configured with the option `low-end mobile or slow 3G` under `Network`. The file only resource being loaded is a SVG file that is 15KB is size.

**Comment by aFarkas** [comment]
@ryanhallinger 
I haven't forgotten you but a lot on my plate.

**Comment by ryanhallinger** [comment]
Thanks for the update Alexander.

Testing it further, the issue occurs each time when `low-end` mobile`. This has to be selected from the menu from the left pane when using the developer tools. Interestingly, the issue I had encountered when choosing `slow 3G` only repeats after `low-end mobile` is used.
