### ISSUE TITLE
Unexpectedly high usage on espn.com

### ISSUE THREAD

**Issue by paulirish** [aFarkas/lazysizes#85]
The espn.com redesign uses lazysizes... 

But from what what I can tell its running checkElements VERY often. If the homepage is up, just scrolling it around a bit will end up calling `checkElements` >80 times in like 15 seconds.

I'm using this to check btw: 
![image](https://cloud.githubusercontent.com/assets/39191/6999607/3bd8c324-dbc4-11e4-9154-40e340f5b6c7.png)

I don't think this is expected behavior. Maybe you could look into this?

**Comment by paulirish** [comment]
Also... this is in Chrome on Android, which has picture support.. so I'm not sure why it's running at all.

**Comment by aFarkas** [comment]
@paulirish 
I had not time to look deeper into this, but lazysizes is not a picture polyfill it is a lazy image loader. So it is expected and designed to be called on a very high frequency. 

So question is:  Does it harm performance? From my experience it should be mostly execute below 0.Xms.

All this said I could throttle it more, but would like to know whether you experience some harm.

One question about browser apis: The check function is run throttled via ``setInterval``, but sometimes trashes layout. Something that I'm asking myself is whether we can utilize ``requestAnimationFrame`` or another API to get timing after (not before) layout should be done by the browser? (A mix with ``requestAnimationFrame`` and ``setTimeout`` for example).

**Comment by paulirish** [comment]
![image](https://cloud.githubusercontent.com/assets/39191/7005683/387e3b6c-dc2f-11e4-8497-e7bdb1d12ef3.png)

Yeah here's lazysizes during pageload on espn. 340ms in total. 

Here's another during scrolling the page:
![image](https://cloud.githubusercontent.com/assets/39191/7005754/f6da3f0c-dc2f-11e4-9948-709f2f384911.png)



rAF is scheduled right before recalc/layout.. You can try a setTimeout(0) from within a rAF to get a callback after layout.

**Comment by aFarkas** [comment]
I have some ideas to improve this. But need to test and have no time today and the next 3. So it will take some time. But it will be (hopefully) great.

In case you have contact to the developers of espn, you can tell them, that they can remove the ``data-sizes="auto"`` attribute. This attribute should be used to calculate the ``sizes`` attribute, which should be used in conjunction with the width descriptor (``w``). But espn is only using the density descriptor (``x``). This means that ``sizeElement`` and partially ``addClass`` and ``setAttribute`` shouldn't be called at all.

About the total numbers in general: As said it is designed to be called frequently, but the browser should have a lot of time to do it's job between those calls. In case the check elements function is [running longer than 3ms, it is aborted](https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L229) (I don't know any other lazyloader, that is doing this).

About the last scrolling flame chart: I don't think this is a normal/median view of those 80 calls. Because the methods ``unveilElement``, ``addClass``, ``sizesElement`` are only invoked, if ``checkElements`` finds an image that has to be transformed, if you watch your network panel you will see, that this is mostly only happening if you stop scrolling or slow down scrolling.

All this said, I'm eager to dive deeper into this :-).

**Comment by paulirish** [comment]
> . In case the check elements function is running longer than 3ms, it is aborted 

That's veryyyy very cool. :) Nice one.

> In case you have contact to the developers of espn
I pinged them from this doc we're collaborating on here:
https://docs.google.com/a/chromium.org/document/d/1yJoMEdFME04maB_hlGhARTeys-DdeHRqU7zn-z4CFcA/edit#

**Comment by paulirish** [comment]
@aFarkas question for you..

What would you need from the browser in order to avoid polling?  

My guess: some notification when elements of interest are about to enter the viewport?

**Comment by paulirish** [comment]
One more aspect here. During pageload there is going to be lots of DOM changes that will end up having lazysizes force layouts. Can you have a much higher poll rate until window.load?

**Comment by aFarkas** [comment]
First of thank you. I have done some bigger improvements. And just released it as [1.1.0-rc2](https://github.com/aFarkas/lazysizes/releases/tag/1.1.0-rc2).

Here is basically what I did:
1. Rewrite of the throttle function (should invoke with less forced layouts)
2. Increase of throttling in general
3. Separate all read write operations and schedule all write operation with rAF.

So here are some numbers. During pageload on my machine lazysizes was called multiple times and took 70ms in total. After those improvements it still is called multiple times (but less often) and takes 25ms in total. From there we can still improve this to about 10ms with some manual configuration (But later).

So here are some charts. This first chart you showed, looked something like this on my machine:

![old-1](https://cloud.githubusercontent.com/assets/188254/7105069/9fea65ba-e106-11e4-92a4-464a4c52bcf3.png)

After those optimizations this call is absolutely gone. So instead of 33ms blocking you get 0ms.

The next invocation looked something like this:

![old-2](https://cloud.githubusercontent.com/assets/188254/7105074/fc6e1c46-e106-11e4-8a46-1d73991db792.png)

And here is the same part with the new version:

![new-2](https://cloud.githubusercontent.com/assets/188254/7105077/0e4fee76-e107-11e4-985c-d629244b8c1e.png)


And here just to complete it the third invocation before:

![old-3](https://cloud.githubusercontent.com/assets/188254/7105083/4c4aa568-e107-11e4-97a8-d079267dd8f5.png)

And after:
![new-3](https://cloud.githubusercontent.com/assets/188254/7105084/5513712a-e107-11e4-8686-c1c4cc5eea70.png)


So as I said manually you can improve this. In general lazysizes trys to check for inview images while the DOM is parsed, this is a) not done with polling, but with mutationobserver and b) this can be a huge network advantage over old school lazyloader, which only start to check and load on domcontentloaded. However it also adds some pressure to the runtime and if you are basically doing a lot of DOM changes during pageload, can be not so efficient.

In that case you can simply pause execution of lazysizes using the loadmode option. Here is an example:

```js
lazySizesConfig.loadMode = 0; //paused

/* heavy stuff */

//some time later
lazySizesConfig.loadMode = 3; //or 2 or 1 depending on the situation you are in
//if you have paused execution with 0 you also need to call explicitly
lazySizes.loader.checkElems();
```

I also added with the RC2 a throttle option, that can be dynamically changed. With this you can do something like this:

```js
lazySizesConfig.throttle = 400;

addEventListener('load', function(){
    lazySizesConfig.throttle = 140;
});
```

But from my testing, I needed to add a throttle of 800+ to improve timings after the 1.1.0 optimizations, I have done. Which means, the lazyloader was basically paused.

I might post a full config for espn wich makes runtime fast, but loads images as soon as possible.

In case you are also testing perf on non Chrome browsers and perf of picturefill is problematic, I would like to here, how this compares to the following version of [picturefill (3.0 proposal)](https://github.com/scottjehl/picturefill/blob/afarkas-pf3-proposal/dist/picturefill.js).

In general, yeah if I have an event that gives me information, whether an element is entering the viewport  (the rectangle of the viewport must be customizable (expandable/shrinkable)), would be much more efficient. Another thing that would help is something like a requestLayoutFrame/requestIdleFrame or something like this. While the after rAF pattern helped, it does not guarantee that I don't force layout and I think this can only accomplished interoperable, if there is a standard.

**Comment by aFarkas** [comment]
I re-thought this with the custom configuration. And my current advise is to only update to the newest RC or [master branch version](https://github.com/aFarkas/lazysizes/blob/master/lazysizes.js), remove the unneeded ``data-sizes="auto"`` without any substitution, remove the deprecated scrollintent plugin and do only the following configuration:

```js
window.lazySizesConfig = window.lazySizesConfig || {};
window.lazySizesConfig. loadMode = 1;
```

Reason: While testing showed, that I can get more performance (10ms vs 25ms) on espn with some lazysizes pausing and re-running, these performance improvements will automatically also be reached, if you fix the other issues. As explained above lazysizes does not poll, but automatically re-acts to DOM changes, so in case you have to do DOM changes while page load, you should do most of them at once instead of doing some changes, than wait, than maybe read and than write again. As soon as this is fixed/optimized you will have less reflows in general and lazysizes is automatically also called less often. 

In general: I'm quite happy with the perf improvements in this version (so I really have to thank you for this issue) (going from 70ms to 25ms). Can you keep me informed pretty curious how this evolves.

**Comment by aFarkas** [comment]
@paulirish 
It seems, I'm not totally done yet ;-).

But I would need some feedback on this, because it is quite hack-y and I can't .

So my current throttle function looks something like this:

```js
var throttle = function(fn){
	var running;
	var lastTime = 0;
	var run = function(){
		running = false;
		lastTime = Date.now();
		fn();
	};
	var afterRAF = function(){
		setTimeout(run);
	};
	var getRAF = function(){
		rAF(afterRAF);
	};

	return function(){
		if(running){
			return;
		}
		var delay = lazySizesConfig.throttle - (Date.now() - lastTime);

		running =  true;

		if(delay < 9){
			delay = 9;
		}
		setTimeout(getRAF, delay);
	};
};
```

I thought about a way to automatically increase the throttle, if there is a lot going on and came up with this:

```js
var throttle = function(fn){
	var running, runs, toRun;
	var lastTime = 0;
	var run = function(){
		running = false;
		lastTime = Date.now();
		fn();
	};
	var afterRAF = function(){
		setTimeout(run);
	};
	var getRAF = function(){
		if(runs > toRun){
			rAF(afterRAF);
		} else {
			setTimeout(getRAF, 15);
		}
		runs++;
	};

	return function(){
		if(running){
			return;
		}
		toRun = Math.round(lazySizesConfig.throttle - (Date.now() - lastTime) / 15);
		runs = 0;
		running =  true;
		getRAF();
	};
};
````
And in fact this helps a lot (checkElements takes only 10ms in total with 3 invocations, while page is loading) but also generates a lot of noise and small entries in the timeline. I really can't estimate, whether I should like or dislike this pattern. So what do you think about this?

**Comment by paulirish** [comment]
I can yet look at the throttling proposal but I gotta say the new improved
changes to avoid layout thrashing are AWESOME. nice work!​

**Comment by aFarkas** [comment]
Thx

**Comment by aFarkas** [comment]
I'm closing this with the [release of the perf improvements](https://github.com/aFarkas/lazysizes/releases/tag/1.1.0), described above. Feel free to re-open, if you see still bigger problems or have concrete advice.

**Comment by oskarrough** [comment]
@aFarkas you're the man.

**Comment by davidpean** [comment]
@oskarrough @paulirish thanks guys! Haven't had a chance to incorporate these onto espn.com yet, but have been starting on some overall improvements and just saw this thread.

**Comment by davidpean** [comment]
@aFarkas I updated to the latest version and removed the auto sizes attribute. Definitely helped with the multiple recalcs that occured under checkElements. On Chrome Android though, still seeing about ~160ms on page load when it is first invoked. Seems to be due to the one recalc it does. It causes several get innerWidths that take 50-70ms each (from the forced recalc from https://github.com/aFarkas/lazysizes/blob/gh-pages/lazysizes.js#L213 according to DevTools). Still need to dig into it more, but that's what I'm seeing so far.

**Comment by davidpean** [comment]
![screenshot 2015-05-06 10 04 29](https://cloud.githubusercontent.com/assets/317856/7495243/b3892372-f3da-11e4-9539-a0f1823d74c4.png)

**Comment by aFarkas** [comment]
@davidpean 
This is weird because ``innerWidth`` is only accessed once, only in case you are using an additional ``data-expand`` attribute it might be accessed multiple times in one loop. Also lazysizes does not write any styles inside of the checkElements cycle so accessing ``innerWidth`` shouldn't trigger a re-calculation. 

Until now, I checked it only with Chrome for desktop. I will try to do some research with android too.

**Comment by aFarkas** [comment]
Will take some time. Next week....

**Comment by davidpean** [comment]
@aFarkas yeah very strange, I'm going to keep looking into it and will let you know what I find. Thanks!

**Comment by aFarkas** [comment]
I'm currently in warsaw, but will have a look, just not to check how to proxy android through charles http debugger to manipulate espn.

**Comment by aFarkas** [comment]
@davidpean 
I could test with android and charles now. I could also get some perf improvement by again refining the throttle function a little bit. Currently only in master branch.

About the multiple calls to ``innerWidth``, I think this is either a bug with chrome inspected timeline or a feature that I don't understand. Because I see a lot of multiple function calls (for example sb.init -> initCallback or onGoogleAdsJsLoad ) although those functions are clearly only invoked once.

Please check the latest version and let me know your findings. In general from looking into the timeline. lazySizes shouldn't be a problem anymore, if it was one. The most time is spend in other widgets. Most notable in the score board and by the google ad service.

**Comment by davidpean** [comment]
@aFarkas definitely not saying this was our #1 concern, just a small win if it was something fixable -- we are addressing those big ones too! I will check out your changes

**Comment by aFarkas** [comment]
Yeah, I'm quite happy with this issue, it helped much to improve things.

I think you can squeeze out some perf, with a little bit of config.

For example:

```js
window.lazySizesConfig = window.lazySizesConfig || {};

lazySizesConfig.loadMode = 1;

lazySizesConfig.throttle = 600;
window.addEventListener('load', function(){
	lazySizesConfig.throttle = 150;
});
```

Also note: that I have removed the scrollintent plugin, it's now partially integrated into lazysizes.
