### ISSUE TITLE
How to Use Lazysizes For Child of Component

### ISSUE THREAD

**Issue by kuroshhashemi** [aFarkas/lazysizes#853]
**Describe the bug**
I'm using the [Ant Design](https://ant.design/components/avatar/) library for UX components.  I use Ant's avatar component with lazysizes <Avatar data-src="someurl" className="lazyload" />.  I expect the avatar to lazy load but it doesn't because Ant renders a <span> with <img> inside it for the actual image.  I assume the same challenge exists with any component that isn't directly an image.

**To Reproduce**
Use https://ant.design/components/avatar/ with lazysizes

**What is the expected behavior**
Avatar behaved like a lazy load component

**What happened instead**
Avatar acts as if not lazy load component

**In what environment (browser/device etc.) does this bug happen/not happen:**
All

**Comment by aFarkas** [comment]
short answer: https://github.com/aFarkas/lazysizes#js-api---events

This is not a bug. This is an issue tracker. If you don't understand how to use an API you can use stackoverflow. 

I would be happy to help if you would at least provide a jsbin or codepen that a) includes lazysizes and b) includes an ant avatar. Instead you just provide a link to the API of ant avatars. This is not even a valid question on stackoverflow. You have to show some effort to get some helpful answer.

I could answer the same way by just linking to the lazysizes readme, because the answer is documented there. But please don't expect me now to read the ant documentation just to make the minimal connection of those two APIs for you. 

If you can provide a test case where I can reproduce your issue you can re-open this issue.

**Comment by kuroshhashemi** [comment]
@aFarkas my apologies for wasting your time - I'm new to this all, but get where you're coming from. I did check the documentation beforehand but didn't see what I was looking for at the time. Sorry again

**Comment by aFarkas** [comment]
No problem. In the last few months I didn't show my nicest site. So don't be afraid to ask questions in the future.
