### ISSUE TITLE
Too early loading

### ISSUE THREAD

**Issue by tpresing** [aFarkas/lazysizes#858]
Hi, I'm using the lazysizes library with Drupal 7 Picture module. 
My problem is that lots of images loaded, however those are far down on the viewport.
I tried to change these settings:
`
lazySizesConfig.expand = 1;
lazySizesConfig.expFactor = 0.0001;
lazySizes.cfg.hFac = 0.001;
`

I tried out lots of numbers here, but the result is the same.
Am i missing something? So i need to load images later when a user reach above 100px for that specific image. 
I tried it out with the latest lazysizes.

Thank you.

**Comment by aFarkas** [comment]
I get those things a lot and I can ensure you that the default numbers are actually pretty good in preloading images without hurting performance. The `expFactor` is as the documentation just says a factor to calculate the expand factor and therefore needs to be bigger than 1 otherwise you really hurt the logic of the script. You should actually get what you want if you set the `expand` to something like `66` and leave the default values (i.e.: `expFactor: 1.5, hFac: 0.7`).

As you might know without a test case I can not help you. I assume there is either a problem with picking up the config or the images in questions aren't loaded by lazysizes at all. So in case you still have a problem, please help me to reproduce your problem first.

**Comment by tpresing** [comment]
I created a codepen for this:

https://codepen.io/tomasseee/full/OJbVoww

If you inspect the network tab you can see that all of the images are loaded however on 1920x1080 only the first two is visible.

**Comment by aFarkas** [comment]
As you also see in the network tab: The initiator for the image downloads is not the lazysizes script but the html file itself. In the html section you also see that no img as a lazyloaded class, only a lazyload class, but `srcset` attributes. The simple/best solution is to remove all `srcset` attributes from `img`/`source` elements.

Please reopen if this doesn't help.
