### ISSUE TITLE
reinitialize on browser resize 

### ISSUE THREAD

**Issue by alexluncashu** [aFarkas/lazysizes#94]
Hello, 
I can't find in docs if it is possible to reinitialize script on browser resizing or on repositioning phone in landscape or portrait mode. Here is an example: http://www.screencast.com/users/andronic90/folders/Jing/media/ec542d10-93ca-469f-989d-01d0be0fc823
I tried this  lazySizes.autoSizer.checkElems(); but dosen't work.

Thank you for you hard work. Awesome plugin.

**Comment by aFarkas** [comment]
To be honest, I seem to be pretty stupid, because I don't understand the screencast. For me it looks like image aren't loading at all. Is this the problem? What exactly should be re-calculated on resize? Are you using the ``data-sizes="auto"`` feature, ``srcset`` or ``picture``. Maybe you can give me a link to the website?

**Comment by alexluncashu** [comment]
my fault, should add more details. 
yes, on browser resize images aren't loading. here is my snipet. I have included this scripts:
lazysizes, ls.bgset.min.js, ls.include.min.js,ls.unveilhooks.min.js - v1.1.0
and respimage, ri.intrinsic.min.js - v1.4.0

````html
<li class="lazyload fw-ratio-container fw-ratio-9-16" 
style="background-image: url(data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==);" data-bgset="//site.com/theme/wp-content/uploads/2015/01/shutterstock_173026550.jpg 1920w, 
//site.com/theme/wp-content/uploads/2015/01/shutterstock_173026550-300x185.jpg 300w, 
//site.com/theme/wp-content/uploads/2015/01/shutterstock_173026550-1024x633.jpg 1024w, 
//site.com/theme/wp-content/uploads/2015/01/shutterstock_173026550.jpg 1920w" >
```

**Comment by aFarkas** [comment]
For this specific markup you won't need include.min.js, ls.unveilhooks.min.js and ri.intrinsic.min.js.

In general with this setup, new images should be loaded, if images become much larger (not smaller). Due to the fact that the difference between those images are pretty heavy you will not see this, if the image is only getting larger by 100 pixel or so. For testing purposes you can change the numbers for the width descriptors. For example try to find the descriptor width, where the first image is loaded at the smallest viewport and then add a minimal bigger image size to the next image candidate and enlarge your viewport. Then you will see, that images are actually loaded.

In case you want to have more control about when specific images are loaded, I suggest, that you use the following syntax:

```html
<li class="lazyload fw-ratio-container fw-ratio-9-16" 
style="background-image: url(data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==);" data-bgset="//site.com/theme/wp-content/uploads/2015/01/shutterstock_173026550-300x185.jpg   [(max-width: 300px)] | 
//site.com/theme/wp-content/uploads/2015/01/shutterstock_173026550-1024x633.jpg   [(max-width: 1100px)] |  
//site.com/theme/wp-content/uploads/2015/01/shutterstock_173026550.jpg" >
```

This will generate an art directed picture, so lazysizes/respimage will definitely load new images at the breakpoints of 300px and 1100px.

**Comment by aFarkas** [comment]
Please re-open, if this doesn't answer your question/the bug still exists.
